Repository espressomd/espresso, pull requests merged in 2018-09, with the labels that each got.

#2122 Draft release notes
  NEWS
  doc/tutorials/Readme.rst
Labels: Documentation

#2142 core: Removed MOLFORCES feature and functionality.
  maintainer/configs/bla.sh
  maintainer/configs/immersed_boundaries.hpp
  maintainer/configs/maxset.hpp
  maintainer/configs/nocheck-maxset.hpp
  src/core/communication.cpp
  src/core/debug.hpp
  src/core/forces.cpp
  src/core/forces_inline.hpp
  src/core/molforces.cpp
  src/core/molforces.hpp
  src/core/topology.cpp
  src/core/topology.hpp
  src/features.def
Labels: Core

#2169 remove the fake-open from the samples
  samples/debye_hueckel.py
  samples/lj_liquid.py
  samples/lj_liquid_distribution.py
  samples/lj_liquid_structurefactor.py
  samples/p3m.py
  samples/samples_common.py
Labels: Python, Testcase

#2234 doc: Fixed Gay-Bern formula.
  doc/sphinx/inter_non-bonded.rst
Labels: Documentation

#2255 Fixes for OpenSUSE rpm build
  src/core/unit_tests/ParallelScriptInterface_test.cpp
  src/python/espressomd/utils.pyx
Labels: BugFix

#2265 Fix unit test without SSE instructions
  src/core/unit_tests/field_coupling_couplings_test.cpp
Labels: BugFix

#2271 Fix MPI on Ubuntu 18.04 with CUDA
  src/core/communication.cpp
Labels: BugFix

#2272 Test observable_cylindricalLB: Split CPU and GPU Parts and Correct skipIfs
  testsuite/observable_cylindricalLB.py
Labels: BugFix, Testcase

#1924 core: Made transfered data parts for ghosts settable by the caller, r…
  src/core/cells.hpp
  src/core/domain_decomposition.cpp
  src/core/ghosts.cpp
  src/core/ghosts.hpp
  src/core/grid_based_algorithms/lb.cpp
  src/core/virtual_sites/lb_inertialess_tracers.cpp
Labels: Core, Improvement

#2285 Update PDF of tutorial 6 with bibliography
  doc/tutorials/06-active_matter/06-active_matter.pdf
Labels: Documentation
