Repository espressomd/espresso, pull requests merged in 2019-02, with the labels that each got.

#2355 Update particles.rst
  doc/sphinx/particles.rst
Labels: Documentation

#2492 cmake: Fixed doxy-config generation
  .gitlab-ci.yml
  doc/doxygen/CMakeLists.txt
  doc/doxygen/gen_doxyconfig.py
  doc/sphinx/CMakeLists.txt
Labels: BugFix, CI, CMake

#2407 Declarative style for particle update comm
  src/core/collision.cpp
  src/core/communication.cpp
  src/core/communication.hpp
  src/core/particle_data.cpp
  src/core/particle_data.hpp
  src/core/polymer.cpp
  src/core/reaction_ensemble.cpp
  src/core/reaction_ensemble.hpp
  src/core/rotation.hpp
  src/core/unit_tests/Span_test.cpp
  src/core/unit_tests/Vector_test.cpp
  src/core/utils/Span.hpp
  src/core/utils/Vector.hpp
  src/core/utils/type_traits.hpp
  src/core/virtual_sites.cpp
  src/core/virtual_sites/VirtualSitesRelative.cpp
  src/python/espressomd/particle_data.pxd
  src/python/espressomd/particle_data.pyx
  src/python/espressomd/utils.pxd
  testsuite/python/particle.py
Labels: Core, ReadyForReview

#2505 Fixed soft sphere cutoff calculation
  maintainer/configs/maxset.hpp
  src/core/nonbonded_interactions/nonbonded_interaction_data.cpp
  src/core/nonbonded_interactions/nonbonded_interaction_data.hpp
  src/python/espressomd/interactions.pxd
  src/python/espressomd/interactions.pyx
  testsuite/python/interactions_non-bonded.py
Labels: ApiChange, BugFix, Core

#2528 Remove outdated html files in online docs
  .gitlab-ci.yml
Labels: CI, Documentation

#2529 Caliper section markings
  src/profiler/include/profiler/profiler.hpp
  src/python/espressomd/CMakeLists.txt
  src/python/espressomd/c_profiler.pxd
  src/python/espressomd/profiler.pyx
Labels: ReadyForReview

#2526 cmake: separate lib for pdbparser.
  src/CMakeLists.txt
  src/core/CMakeLists.txt
  src/core/io/reader/CMakeLists.txt
  src/core/unit_tests/CMakeLists.txt
  src/pdbparser/CMakeLists.txt
  src/pdbparser/include/PdbParser.hpp
  src/pdbparser/src/PdbParser.cpp
  src/pdbparser/unit_tests/CMakeLists.txt
  src/pdbparser/unit_tests/PdbParser_test.cpp
Labels: ReadyForReview

#2504 Remove MEMD
  doc/sphinx/appendix.rst
  doc/sphinx/electrostatics.rst
  doc/sphinx/installation.rst
  doc/sphinx/introduction.rst
  doc/sphinx/running.rst
  doc/sphinx/zrefs.bib
  maintainer/configs/nocheck-maxset.hpp
  src/config/features.def
  src/core/CMakeLists.txt
  src/core/communication.cpp
  src/core/communication.hpp
  src/core/debug.hpp
  src/core/electrostatics_magnetostatics/CMakeLists.txt
  src/core/electrostatics_magnetostatics/maggs.cpp
  src/core/electrostatics_magnetostatics/maggs.hpp
  src/core/energy.cpp
  src/core/forces.cpp
  src/core/initialize.cpp
  src/core/initialize.hpp
  src/core/integrate.cpp
  src/core/nonbonded_interactions/nonbonded_interaction_data.cpp
  src/core/nonbonded_interactions/nonbonded_interaction_data.hpp
  src/python/espressomd/electrostatics.pxd
Labels: Core

#2537 maintainer: reduce verbosity of coverage upload
  .gitlab-ci.yml
  maintainer/CI/build_cmake.sh
Labels: CI
