Repository espressomd/espresso, pull requests merged in 2019-04, with the labels that each got.

#2593 core: utils: all_gatherv, gatherv fix + tests
  src/core/unit_tests/CMakeLists.txt
  src/core/unit_tests/all_gatherv_test.cpp
  src/core/unit_tests/gatherv_test.cpp
  src/core/utils/mpi/all_gatherv.hpp
  src/core/utils/mpi/gather_buffer.hpp
  src/core/utils/mpi/gatherv.hpp
Labels: Core, ReadyForReview

#2751 Restore Mayavi visualizer’s API-compatibility with OpenGL visualizer
  src/python/espressomd/visualization_mayavi.pyx
Labels: Next, Python

#2677 Visualization: dihedrals connectivity
  src/python/espressomd/visualization_mayavi.pyx
  src/python/espressomd/visualization_opengl.pyx
Labels: Next

#2734 Move developer's guide to the GitHub wiki
  doc/sphinx/CMakeLists.txt
  doc/sphinx/contributing.rst
  doc/sphinx/dg.rst
  doc/sphinx/index.rst
  doc/sphinx/introduction.rst
  doc/sphinx/testing.rst
  src/core/bonded_interactions/bonded_interaction_data.cpp
  src/core/bonded_interactions/bonded_interaction_data.hpp
  src/core/bonded_interactions/bonded_interactions.dox
Labels: Documentation, Next

#2768 CI: Don't override number of build processes on cuda builds
  maintainer/cuda_build.sh
Labels: CI
