Repository espressomd/espresso, pull requests merged in 2019-12, with the labels that each got.

#3356 core: particle_data: Fixed removal of bonds to deleted particles.
  src/core/particle_data.cpp
  testsuite/python/particle.py
Labels: BugFix, Core

#3358 Fix breaking tests on 4.1.1
  .gitlab-ci.yml
  src/core/unit_tests/field_coupling_fields_test.cpp
Labels: CI

#3331 Testcase for ELC and MMM2D
  testsuite/python/CMakeLists.txt
  testsuite/python/elc_and_mmm2d_vs_analytic.py
Labels: Testcase

#3373 Update maintainer scripts
  AUTHORS
  maintainer/add_missing_headers.sh
  maintainer/find_potentially_missing_authors.sh
  maintainer/update_header.sh
Labels: automerge

#3367 py: ParticleSlice fixes
  doc/sphinx/particles.rst
  maintainer/CI/doc_warnings.sh
  src/python/espressomd/analyze.pyx
  src/python/espressomd/particle_data.pyx
  testsuite/python/cluster_analysis.py
  testsuite/python/particle.py
Labels: Next, automerge

#3388 Fix velocity Verlet interface
  src/python/espressomd/integrate.pyx
Labels: BugFix, automerge
