Repository espressomd/espresso, pull requests merged in 2020-02, with the labels that each got.

#3444 Refactor thermostats: RNG, callbacks and documentation
  doc/doxygen/Doxyfile.in
  doc/sphinx/running.rst
  doc/sphinx/system_setup.rst
  samples/visualization_npt.py
  src/core/integrate.cpp
  src/core/integrators/velocity_verlet_npt.cpp
  src/core/random.hpp
  src/core/thermostat.cpp
  src/core/thermostat.hpp
  src/core/unit_tests/CMakeLists.txt
  src/core/unit_tests/random_test.cpp
  src/core/unit_tests/random_test.hpp
  src/core/unit_tests/thermostats_test.cpp
  src/python/espressomd/thermostat.pxd
  src/python/espressomd/thermostat.pyx
  testsuite/python/integrator_npt.py
  testsuite/python/save_checkpoint.py
  testsuite/python/test_checkpoint.py
Labels: ApiChange, Core, Documentation, Testcase, automerge

#3447 Fix test for intel image
  src/core/unit_tests/thermostats_test.cpp
Labels: CI, automerge

#3448 Cleanup analyze module
  doc/tutorials/02-charged_system/02-charged_system-1.ipynb
  src/core/observables/ComForce.hpp
  src/core/observables/PidObservable.hpp
  src/python/espressomd/analyze.pyx
  src/script_interface/observables/PidObservable.hpp
  testsuite/python/analyze_distribution.py
Labels: Documentation, Python, automerge

#3446 maintainer: Handle generation of handling of external features in con…
  src/config/gen_featureconfig.py
Labels: automerge

#3340 core: Removed MMM2d
  doc/sphinx/electrostatics.rst
  doc/sphinx/introduction.rst
  samples/visualization_mmm2d.py
  src/core/CMakeLists.txt
  src/core/electrostatics_magnetostatics/coulomb.cpp
  src/core/electrostatics_magnetostatics/coulomb.hpp
  src/core/electrostatics_magnetostatics/coulomb_inline.hpp
  src/core/electrostatics_magnetostatics/elc.hpp
  src/core/electrostatics_magnetostatics/mmm2d.cpp
  src/core/electrostatics_magnetostatics/mmm2d.hpp
  src/python/espressomd/electrostatics.pxd
  src/python/espressomd/electrostatics.pyx
  testsuite/python/CMakeLists.txt
  testsuite/python/coulomb_mixed_periodicity.py
  testsuite/python/elc_vs_analytic.py
  testsuite/python/elc_vs_mmm2d_neutral.py
  testsuite/python/elc_vs_mmm2d_nonneutral.py
  testsuite/scripts/samples/CMakeLists.txt
  testsuite/scripts/samples/test_visualization_mmm2d.py
Labels: Core, Improvement, automerge

#3452 testsuite: refactor array test.
  testsuite/python/array_properties.py
Labels: Python, Testcase, automerge

#3461 Refactor thermostats: RNG and code duplication
  src/core/bonded_interactions/thermalized_bond.cpp
  src/core/bonded_interactions/thermalized_bond.hpp
  src/core/dpd.cpp
  src/core/dpd.hpp
  src/core/grid_based_algorithms/lb_particle_coupling.cpp
  src/core/integrate.cpp
  src/core/integrators/brownian_inline.hpp
  src/core/integrators/langevin_inline.hpp
  src/core/random.hpp
  src/core/thermostat.cpp
  src/core/thermostat.hpp
  src/core/unit_tests/random_test.cpp
  src/core/unit_tests/thermostats_test.cpp
  src/python/espressomd/interactions.pxd
  src/python/espressomd/thermostat.pxd
  testsuite/python/rotation.py
Labels: BugFix, Core, Improvement, automerge

#3466 Get rid of unused variables in shapes.
  src/core/shapes/Ellipsoid.cpp
  src/core/shapes/Stomatocyte.cpp
Labels: automerge

#3469 Fix issue in a docstring for recent sphinx versions
  src/python/espressomd/observables.py
Labels: BugFix, Documentation, automerge

#3470 Remove cylindrical_average.
  doc/sphinx/analysis.rst
  doc/sphinx/figures/analysis_cylindrical_average.png
  src/core/statistics.cpp
  src/core/statistics.hpp
  src/python/espressomd/analyze.pxd
  src/python/espressomd/analyze.pyx
Labels: automerge

#3471 Rename observable ComForce to TotalForce.
  doc/sphinx/analysis.rst
  src/core/observables/TotalForce.hpp
  src/python/espressomd/observables.py
  src/script_interface/observables/initialize.cpp
  testsuite/python/observables.py
Labels: automerge

#3468 Fix ELC sample
  doc/sphinx/analysis.rst
  doc/sphinx/appendix.rst
  doc/sphinx/electrostatics.rst
  doc/sphinx/magnetostatics.rst
  doc/sphinx/under_the_hood.rst
  samples/p3m.py
  samples/visualization_elc.py
  src/core/collision.cpp
  src/core/energy.hpp
  src/core/forces.hpp
  src/core/pressure.cpp
  src/python/espressomd/electrostatic_extensions.pyx
  src/python/espressomd/electrostatics.pyx
  src/python/espressomd/magnetostatic_extensions.pyx
  src/python/espressomd/magnetostatics.pyx
  testsuite/scripts/samples/CMakeLists.txt
  testsuite/scripts/samples/test_visualization_elc.py
Labels: CodingDay, Documentation, Testcase, automerge

#3463 Cone shape
  doc/doxygen/figs/conical_frustum.png
  doc/sphinx/constraints.rst
  doc/sphinx/figures/conical_frustum.png
  doc/sphinx/figures/conical_frustum.svg
  doc/sphinx/figures/shape-conical_frustum.png
  doc/sphinx/figures/shape-hollowcone.png
  doc/tutorials/06-active_matter/06-active_matter.ipynb
  doc/tutorials/06-active_matter/EXERCISES/rectification_geometry.py
  doc/tutorials/06-active_matter/EXERCISES/rectification_simulation.py
  doc/tutorials/06-active_matter/SOLUTIONS/rectification_geometry.py
  doc/tutorials/06-active_matter/SOLUTIONS/rectification_simulation.py
  doc/tutorials/html_runner.py
  samples/visualization_constraints.py
  src/core/shapes/CMakeLists.txt
  src/core/shapes/HollowCone.cpp
  src/core/shapes/HollowCone.hpp
  src/core/shapes/HollowConicalFrustum.cpp
  src/core/shapes/HollowConicalFrustum.hpp
  src/core/shapes/Sphere.cpp
  src/core/shapes/unit_tests/CMakeLists.txt
  src/core/shapes/unit_tests/Ellipsoid_test.cpp
  src/core/shapes/unit_tests/HollowConicalFrustum_test.cpp
  src/core/shapes/unit_tests/Wall_test.cpp
  src/core/unit_tests/CMakeLists.txt
  src/python/espressomd/shapes.py
  src/script_interface/shapes/HollowCone.hpp
  src/script_interface/shapes/HollowConicalFrustum.hpp
  src/script_interface/shapes/initialize.cpp
  testsuite/python/constraint_shape_based.py
  testsuite/scripts/samples/CMakeLists.txt
Labels: ReadyForReview, automerge

#3467 Update shapes code
  src/core/integrators/velocity_verlet_npt.cpp
  src/core/shapes/Ellipsoid.cpp
  src/core/shapes/Rhomboid.cpp
  src/core/shapes/SimplePore.cpp
  src/core/shapes/Stomatocyte.cpp
Labels: BugFix, CodingDay, Core, automerge

#3477 Diamond Polymers in Python
  doc/sphinx/particles.rst
  doc/tutorials/04-lattice_boltzmann/04-lattice_boltzmann_part3.ipynb
  doc/tutorials/04-lattice_boltzmann/scripts/04-lattice_boltzmann_part3_solution.py
  doc/tutorials/12-constant_pH/12-constant_pH.ipynb
  samples/constraints.py
  samples/electrophoresis.py
  samples/h5md.py
  samples/minimal-diamond.py
  samples/minimal-polymer.py
  src/core/CMakeLists.txt
  src/core/diamond.cpp
  src/core/diamond.hpp
  src/python/espressomd/diamond.pxd
  src/python/espressomd/diamond.pyx
  src/python/espressomd/polymer.pyx
  testsuite/python/CMakeLists.txt
  testsuite/python/analyze_chains.py
  testsuite/python/polymer_diamond.py
  testsuite/python/polymer_linear.py
Labels: ApiChange, Python, Testcase, automerge

#3479 doc: fix active matter tutorial.
  doc/tutorials/06-active_matter/SOLUTIONS/rectification_simulation.py
Labels: automerge

#3480 Update documentation
  doc/sphinx/CMakeLists.txt
  doc/sphinx/analysis.rst
  doc/sphinx/conf.py.in
  doc/sphinx/constraints.rst
  doc/sphinx/figures/basepair.pdf
  doc/sphinx/figures/basepair.svg
  doc/sphinx/inter_non-bonded.rst
  doc/sphinx/introduction.rst
  doc/sphinx/particles.rst
  doc/sphinx/under_the_hood.rst
  maintainer/CI/doc_warnings.sh
  src/python/espressomd/pair_criteria.py
  src/python/espressomd/particle_data.pyx
Labels: Documentation, automerge

#3484 Fix polymer generation
  src/core/polymer.cpp
Labels: BugFix, Core, automerge

#3486 Improve CMake logic for tutorials
  doc/tutorials/01-lennard_jones/CMakeLists.txt
  doc/tutorials/02-charged_system/CMakeLists.txt
  doc/tutorials/04-lattice_boltzmann/CMakeLists.txt
  doc/tutorials/04-lattice_boltzmann/scripts/04-lattice_boltzmann_part4_solution_cut.cmake
  doc/tutorials/05-raspberry_electrophoresis/CMakeLists.txt
  doc/tutorials/06-active_matter/CMakeLists.txt
  doc/tutorials/07-electrokinetics/CMakeLists.txt
  doc/tutorials/08-visualization/CMakeLists.txt
  doc/tutorials/11-ferrofluid/CMakeLists.txt
  doc/tutorials/12-constant_pH/CMakeLists.txt
  doc/tutorials/CMakeLists.txt
  testsuite/scripts/tutorials/CMakeLists.txt
Labels: CMake, Improvement, automerge

#3491 Remove infinite loop in linear polymer
  src/core/polymer.cpp
  testsuite/python/polymer_linear.py
Labels: BugFix, automerge

#3496 Cleanup cython
  src/core/particle_data.cpp
  src/python/espressomd/__init__.py
  src/python/espressomd/actors.pyx
  src/python/espressomd/analyze.pxd
  src/python/espressomd/analyze.pyx
  src/python/espressomd/cellsystem.pxd
  src/python/espressomd/cellsystem.pyx
  src/python/espressomd/checkpointing.py
  src/python/espressomd/collision_detection.pyx
  src/python/espressomd/drude_helpers.py
  src/python/espressomd/electrokinetics.pxd
  src/python/espressomd/electrokinetics.pyx
  src/python/espressomd/electrostatic_extensions.pxd
  src/python/espressomd/electrostatic_extensions.pyx
  src/python/espressomd/electrostatics.pxd
  src/python/espressomd/electrostatics.pyx
  src/python/espressomd/globals.pxd
  src/python/espressomd/globals.pyx
  src/python/espressomd/grid.pxd
  src/python/espressomd/integrate.pxd
  src/python/espressomd/integrate.pyx
  src/python/espressomd/interactions.pxd
  src/python/espressomd/interactions.pyx
  src/python/espressomd/lb.pyx
  src/python/espressomd/magnetostatic_extensions.pxd
  src/python/espressomd/magnetostatic_extensions.pyx
  src/python/espressomd/magnetostatics.pxd
  src/python/espressomd/magnetostatics.pyx
  src/python/espressomd/particle_data.pxd
  src/python/espressomd/particle_data.pyx
  src/python/espressomd/polymer.pyx
  src/python/espressomd/profiler.pyx
  src/python/espressomd/reaction_ensemble.pyx
  src/python/espressomd/scafacos.pyx
  src/python/espressomd/script_interface.pxd
  src/python/espressomd/script_interface.pyx
  src/python/espressomd/system.pxd
  src/python/espressomd/system.pyx
  src/python/espressomd/thermostat.pyx
  src/python/espressomd/version.pyx
  src/python/espressomd/visualization_mayavi.pyx
  src/python/espressomd/visualization_opengl.pyx
Labels: BugFix, Core, Improvement, Python, automerge

#3499 core: Removed unused global
  src/core/global.cpp
  src/core/global.hpp
  src/core/particle_data.cpp
  src/core/particle_data.hpp
  src/python/espressomd/globals.pxd
  src/python/espressomd/particle_data.pyx
Labels: automerge

#3501 Expose `local_particles` only thru function calls
  src/core/PartCfg.hpp
  src/core/cells.cpp
  src/core/collision.cpp
  src/core/communication.cpp
  src/core/debug.cpp
  src/core/domain_decomposition.cpp
  src/core/energy_inline.hpp
  src/core/event.cpp
  src/core/forces_inline.hpp
  src/core/ghosts.cpp
  src/core/grid_based_algorithms/lbgpu.cpp
  src/core/immersed_boundary/ImmersedBoundaries.cpp
  src/core/io/mpiio/mpiio.cpp
  src/core/io/writer/h5md_core.cpp
  src/core/layered.cpp
  src/core/nsquare.cpp
  src/core/object-in-fluid/oif_global_forces.cpp
  src/core/particle_data.cpp
  src/core/particle_data.hpp
  src/core/pressure_inline.hpp
  src/core/rattle.cpp
  src/core/reaction_ensemble.hpp
  src/core/virtual_sites.cpp
  src/core/virtual_sites/VirtualSitesRelative.cpp
  src/utils/include/utils/SkipIterator.hpp
  src/utils/tests/CMakeLists.txt
  src/utils/tests/SkipIterator_test.cpp
Labels: Core, Improvement, automerge

#3385 Oif corrections
  maintainer/configs/maxset.hpp
  samples/object_in_fluid/motivation.py
  src/config/features.def
  src/core/forces.cpp
  src/core/forces_inline.hpp
  src/core/global.cpp
  src/core/object-in-fluid/oif_local_forces.hpp
  src/python/espressomd/system.pyx
  src/python/object_in_fluid/oif_utils.py
  src/utils/include/utils/math/triangle_functions.hpp
  src/utils/tests/triangle_functions_test.cpp
  testsuite/python/oif_volume_conservation.py
Labels: automerge

#3505 Remove max_seen_particle global from python interface
  src/core/particle_data.cpp
  src/core/particle_data.hpp
  src/core/reaction_ensemble.cpp
  src/python/espressomd/globals.pxd
  src/python/espressomd/particle_data.pxd
  src/python/espressomd/particle_data.pyx
Labels: Improvement, Python, automerge

#3493 Shape union
  doc/sphinx/constraints.rst
  src/core/grid_based_algorithms/lb_boundaries.cpp
  src/core/shapes/CMakeLists.txt
  src/core/shapes/Shape.hpp
  src/core/shapes/Union.hpp
  src/core/shapes/unit_tests/CMakeLists.txt
  src/core/shapes/unit_tests/Union_test.cpp
  src/python/espressomd/shapes.py
  src/script_interface/shapes/Union.hpp
  src/script_interface/shapes/initialize.cpp
  testsuite/python/CMakeLists.txt
  testsuite/python/shapes.py
Labels: automerge

#3509 Fix electrophoresis sample test
  testsuite/scripts/samples/test_electrophoresis.py
Labels: CI, Next, automerge

#3510 Cleanup cython further
  src/python/espressomd/analyze.pxd
  src/python/espressomd/cellsystem.pxd
  src/python/espressomd/cellsystem.pyx
  src/python/espressomd/electrokinetics.pyx
  src/python/espressomd/electrostatics.pxd
  src/python/espressomd/globals.pxd
  src/python/espressomd/integrate.pxd
  src/python/espressomd/integrate.pyx
  src/python/espressomd/interactions.pxd
  src/python/espressomd/lb.pyx
  src/python/espressomd/magnetostatics.pxd
  src/python/espressomd/magnetostatics.pyx
  src/python/espressomd/particle_data.pxd
  src/python/espressomd/particle_data.pyx
  src/python/espressomd/thermostat.pxd
  src/python/espressomd/thermostat.pyx
  src/python/espressomd/utils.pxd
  src/python/espressomd/visualization_opengl.pyx
Labels: Improvement, Python, automerge

#3511 Fix bond drawing bugs in the OpenGL visualizer
  src/python/espressomd/visualization_opengl.pyx
Labels: BugFix, automerge

#3512 Layered
  doc/sphinx/system_setup.rst
  src/core/CMakeLists.txt
  src/core/cells.cpp
  src/core/cells.hpp
  src/core/electrostatics_magnetostatics/coulomb.cpp
  src/core/global.cpp
  src/core/global.hpp
  src/core/layered.cpp
  src/core/layered.hpp
  src/core/short_range_loop.hpp
  src/python/espressomd/cellsystem.pxd
  src/python/espressomd/cellsystem.pyx
  testsuite/python/CMakeLists.txt
  testsuite/python/cellsystem.py
  testsuite/python/layered.py
  testsuite/python/pairs.py
  testsuite/python/random_pairs.py
Labels: ApiChange, Core, Improvement, Python, automerge

#3533 Fix memory leak in OpenGL visualizer
  samples/visualization_constraints.py
  src/python/espressomd/visualization_opengl.pyx
  testsuite/scripts/samples/test_visualization_constraints.py
Labels: BugFix, Testcase, automerge

#3536 Fix TypeError in System.number_of_particles()
  src/core/grid_based_algorithms/electrokinetics.hpp
  src/python/espressomd/electrokinetics.pxd
  src/python/espressomd/electrostatics.pxd
  src/python/espressomd/lb.pxd
  src/python/espressomd/particle_data.pxd
  src/python/espressomd/script_interface.pxd
  src/python/espressomd/system.pyx
Labels: Improvement, Python, automerge

#3542 Sphinx: fix code samples (instantiation and naming of System())
  doc/sphinx/advanced_methods.rst
  doc/sphinx/analysis.rst
  doc/sphinx/lb.rst
  doc/sphinx/particles.rst
  doc/sphinx/running.rst
  doc/sphinx/system_setup.rst
Labels: Documentation, automerge

#3538 Opengl rasterization for union
  src/core/shapes/Union.hpp
  src/python/espressomd/visualization_opengl.pyx
  testsuite/python/lb_boundary.py
  testsuite/python/shapes.py
Labels: automerge

#3544 Removed max_seen_particle global
  src/core/collision.cpp
  src/core/debug.cpp
  src/core/global.cpp
  src/core/global.hpp
  src/core/io/mpiio/mpiio.cpp
  src/core/particle_data.cpp
  src/core/particle_data.hpp
Labels: Core, Improvement, automerge

#3359 Added a Gibbs ensemble Monte Carlo sample
  samples/gibbs_ensemble_client.py
  samples/gibbs_ensemble_socket.py
  testsuite/scripts/samples/CMakeLists.txt
  testsuite/scripts/samples/test_gibbs_ensemble.py
Labels: automerge

#3549 Fix failing sample test in CI
  samples/gibbs_ensemble_client.py
  samples/gibbs_ensemble_socket.py
  testsuite/scripts/samples/test_gibbs_ensemble.py
Labels: Next, automerge
