Repository espressomd/espresso, pull requests merged in 2020-01, with the labels that each got.

#3393 Disable Sphinx multiprocessing
  doc/sphinx/CMakeLists.txt
Labels: CI, automerge

#3391 utils: Test for triangle normal calculation.
  src/utils/include/utils/math/triangle_functions.hpp
  src/utils/tests/CMakeLists.txt
  src/utils/tests/triangle_functions_test.cpp
Labels: Core, Testcase, automerge

#3375 Update requirements
  .gitlab-ci.yml
  CMakeLists.txt
  testsuite/CMakeLists.txt
Labels: CMake, automerge

#3395 Remove LaTeX dependency
  doc/CMakeLists.txt
  doc/latexit.sh.in
  doc/misc/bibliography.bib
  doc/misc/python.tex
  doc/sphinx/contributing.rst
  doc/tutorials/01-lennard_jones/01-lennard_jones.ipynb
  doc/tutorials/02-charged_system/02-charged_system-1.ipynb
  doc/tutorials/06-active_matter/06-active_matter.ipynb
  doc/tutorials/06-active_matter/06-active_matter.tex
  doc/tutorials/06-active_matter/CMakeLists.txt
  doc/tutorials/06-active_matter/FIGURES/enhanced.svg
  doc/tutorials/06-active_matter/FIGURES/flow_field.svg
  doc/tutorials/06-active_matter/FIGURES/friction.svg
  doc/tutorials/06-active_matter/FIGURES/geometry.svg
  doc/tutorials/06-active_matter/FIGURES/pusher-puller.svg
  doc/tutorials/06-active_matter/FIGURES/rectification.svg
  doc/tutorials/06-active_matter/FIGURES/rectify.svg
  doc/tutorials/06-active_matter/refs.bib
  doc/tutorials/CMakeLists.txt
  doc/tutorials/Readme.rst
Labels: CMake, Documentation, Improvement, automerge

#3392 Quaternion formalism comments and docs
  doc/doxygen/bibliography.bib
  doc/sphinx/running.rst
  doc/sphinx/zrefs.bib
  src/core/rotation.cpp
Labels: Documentation, automerge

#3397 PidObservable refactoring
  src/core/observables/BondAngles.hpp
  src/core/observables/BondDihedrals.hpp
  src/core/observables/ComForce.hpp
  src/core/observables/ComPosition.hpp
  src/core/observables/ComVelocity.hpp
  src/core/observables/CosPersistenceAngles.hpp
  src/core/observables/Current.hpp
  src/core/observables/CylindricalDensityProfile.hpp
  src/core/observables/CylindricalFluxDensityProfile.hpp
  src/core/observables/CylindricalLBFluxDensityProfileAtParticlePositions.cpp
  src/core/observables/CylindricalLBFluxDensityProfileAtParticlePositions.hpp
  src/core/observables/CylindricalLBVelocityProfileAtParticlePositions.cpp
  src/core/observables/CylindricalLBVelocityProfileAtParticlePositions.hpp
  src/core/observables/CylindricalVelocityProfile.hpp
  src/core/observables/DensityProfile.hpp
  src/core/observables/DipoleMoment.hpp
  src/core/observables/FluxDensityProfile.hpp
  src/core/observables/ForceDensityProfile.hpp
  src/core/observables/MagneticDipoleMoment.hpp
  src/core/observables/ParticleAngularVelocities.hpp
  src/core/observables/ParticleBodyAngularVelocities.hpp
  src/core/observables/ParticleBodyVelocities.hpp
  src/core/observables/ParticleDistances.hpp
  src/core/observables/ParticleForces.hpp
  src/core/observables/ParticlePositions.hpp
  src/core/observables/ParticleVelocities.hpp
  src/core/observables/PidObservable.cpp
  src/core/observables/PidObservable.hpp
Labels: Core, Improvement, automerge

#3403 core: Fixed erronous feature guards in P3M, fixed missing feature dec…
  src/core/electrostatics_magnetostatics/p3m_send_mesh.cpp
  src/core/electrostatics_magnetostatics/p3m_send_mesh.hpp
  testsuite/python/dawaanr-and-bh-gpu.py
  testsuite/python/dawaanr-and-dds-gpu.py
  testsuite/python/dds-and-bh-gpu.py
Labels: automerge

#3402 Reuse distto from statistics in polymer/diamond code, fix minor perfo…
  src/core/diamond.cpp
  src/core/diamond.hpp
  src/core/polymer.cpp
  src/core/polymer.hpp
  src/core/statistics.hpp
Labels: automerge

#3404 statistics_chains cleanup
  src/core/communication.cpp
  src/core/statistics_chain.cpp
  src/core/statistics_chain.hpp
  src/python/espressomd/analyze.pxd
  src/python/espressomd/analyze.pyx
Labels: automerge

#3398 Moved local cells/ghost_cells global into class
  src/core/EspressoSystemInterface.cpp
  src/core/cells.cpp
  src/core/cells.hpp
  src/core/collision.cpp
  src/core/debug.cpp
  src/core/domain_decomposition.cpp
  src/core/electrostatics_magnetostatics/coulomb.cpp
  src/core/electrostatics_magnetostatics/mdlc_correction.cpp
  src/core/electrostatics_magnetostatics/mmm2d.cpp
  src/core/electrostatics_magnetostatics/p3m-dipolar.cpp
  src/core/electrostatics_magnetostatics/p3m.cpp
  src/core/electrostatics_magnetostatics/scafacos.cpp
  src/core/energy.cpp
  src/core/forces.cpp
  src/core/galilei.cpp
  src/core/ghosts.hpp
  src/core/immersed_boundary/ImmersedBoundaries.cpp
  src/core/integrate.cpp
  src/core/layered.cpp
  src/core/nsquare.cpp
  src/core/particle_data.cpp
  src/core/pressure.cpp
  src/core/rattle.cpp
  src/core/short_range_loop.hpp
  src/core/statistics.cpp
  src/core/virtual_sites/VirtualSitesInertialessTracers.cpp
  src/core/virtual_sites/VirtualSitesRelative.cpp
  src/core/virtual_sites/lb_inertialess_tracers.cpp
  src/script_interface/h5md/h5md.cpp
Labels: automerge

#3320 Default values for particle is_virtual and ext_flag when not compiled in
  src/core/Particle.hpp
  src/core/collision.hpp
  src/core/cuda_interface.hpp
  src/core/energy_inline.hpp
  src/core/integrators/steepest_descent.cpp
  src/core/integrators/velocity_verlet_inline.hpp
  src/core/integrators/velocity_verlet_npt.cpp
  src/core/particle_data.hpp
Labels: automerge

#3406 samples: make drude sample deterministic.
  samples/drude_bmimpf6.py
Labels: automerge

#3410 Typo.
  doc/sphinx/io.rst
Labels: automerge

#3412 Benchmarks: support all MPI libraries
  maintainer/benchmarks/ferrofluid.py
  maintainer/benchmarks/lj.py
  maintainer/benchmarks/p3m.py
  maintainer/benchmarks/runner.sh
  maintainer/benchmarks/suite.sh
Labels: BugFix, automerge

#3390 Refactor integrator framework to reduce coupling
  doc/sphinx/electrostatics.rst
  doc/sphinx/running.rst
  doc/sphinx/system_setup.rst
  doc/tutorials/02-charged_system/02-charged_system-1.ipynb
  doc/tutorials/02-charged_system/02-charged_system-2.ipynb
  doc/tutorials/02-charged_system/scripts/nacl.py
  doc/tutorials/02-charged_system/scripts/nacl_units_confined.py
  doc/tutorials/02-charged_system/scripts/nacl_units_confined_vis.py
  doc/tutorials/04-lattice_boltzmann/04-lattice_boltzmann_part3.ipynb
  doc/tutorials/04-lattice_boltzmann/scripts/04-lattice_boltzmann_part3_solution.py
  samples/chamber_game.py
  samples/drude_bmimpf6.py
  samples/visualization_bonded.py
  samples/visualization_cellsystem.py
  samples/visualization_charged.py
  samples/visualization_mmm2d.py
  samples/visualization_npt.py
  src/core/MpiCallbacks.hpp
  src/core/actor/Mmm1dgpuForce.hpp
  src/core/communication.cpp
  src/core/communication.hpp
  src/core/cuda_interface.hpp
  src/core/electrostatics_magnetostatics/magnetic_non_p3m_methods.hpp
  src/core/electrostatics_magnetostatics/mdlc_correction.cpp
  src/core/electrostatics_magnetostatics/mdlc_correction.hpp
  src/core/global.cpp
  src/core/global.hpp
  src/core/immersed_boundary/ImmersedBoundaries.cpp
  src/core/integrate.cpp
  src/core/integrate.hpp
  src/core/integrators/steepest_descent.cpp
  src/core/integrators/steepest_descent.hpp
  src/core/pressure.cpp
  src/core/shapes/Cylinder.hpp
  src/core/shapes/HollowCone.hpp
  src/core/shapes/SimplePore.hpp
  src/core/shapes/SpheroCylinder.hpp
  src/core/shapes/Torus.hpp
  src/core/tuning.cpp
  src/core/tuning.hpp
  src/core/unit_tests/MpiCallbacks_test.cpp
  src/core/virtual_sites/lb_inertialess_tracers_cuda.cu
  src/python/espressomd/integrate.pxd
  src/python/espressomd/integrate.pyx
  src/python/espressomd/minimize_energy.pxd
  src/python/espressomd/minimize_energy.pyx
  src/python/espressomd/system.pyx
  testsuite/python/CMakeLists.txt
  testsuite/python/integrator_npt.py
  testsuite/python/integrator_steepest_descent.py
  testsuite/python/minimize_energy.py
  testsuite/python/save_checkpoint.py
  testsuite/python/test_checkpoint.py
Labels: ApiChange, Core, Improvement, automerge

#3414 doc: improve electrophoresis sample.
  samples/electrophoresis.py
  testsuite/scripts/samples/test_electrophoresis.py
Labels: automerge

#3399 Removed ghost flag globals
  src/core/bonded_interactions/bonded_interaction_data.hpp
  src/core/cells.cpp
  src/core/cells.hpp
  src/core/collision.cpp
  src/core/event.cpp
  src/core/event.hpp
  src/core/ghosts.cpp
  src/core/integrate.cpp
  src/core/rattle.cpp
Labels: automerge

#3423 Tutorial 12: support both pint 0.9 and 10.1
  doc/tutorials/12-constant_pH/12-constant_pH.ipynb
Labels: CI, automerge

#3419 Fix broken python tests and refactor assertions
  testsuite/python/actor.py
  testsuite/python/analyze_distance.py
  testsuite/python/analyze_distribution.py
  testsuite/python/analyze_gyration_tensor.py
  testsuite/python/analyze_mass_related.py
  testsuite/python/array_properties.py
  testsuite/python/auto_exclusions.py
  testsuite/python/cluster_analysis.py
  testsuite/python/collision_detection.py
  testsuite/python/coulomb_cloud_wall.py
  testsuite/python/coulomb_cloud_wall_duplicated.py
  testsuite/python/coulomb_mixed_periodicity.py
  testsuite/python/coulomb_tuning.py
  testsuite/python/dpd.py
  testsuite/python/ek_charged_plate.py
  testsuite/python/elc_and_mmm2d_vs_analytic.py
  testsuite/python/elc_vs_mmm2d_neutral.py
  testsuite/python/elc_vs_mmm2d_nonneutral.py
  testsuite/python/exclusions.py
  testsuite/python/h5md.py
  testsuite/python/interactions_bonded_interface.py
  testsuite/python/interactions_non-bonded.py
  testsuite/python/interactions_non-bonded_interface.py
  testsuite/python/langevin_thermostat.py
  testsuite/python/lb_boundary.py
  testsuite/python/lb_thermostat.py
  testsuite/python/mass-and-rinertia_per_particle.py
  testsuite/python/mmm1d.py
  testsuite/python/nsquare.py
  testsuite/python/p3m_gpu.py
  testsuite/python/pairs.py
  testsuite/python/particle_slice.py
  testsuite/python/random_pairs.py
  testsuite/python/rdf.py
  testsuite/python/rigid_bond.py
  testsuite/python/rotational_inertia.py
  testsuite/python/sigint.py
  testsuite/python/stress.py
  testsuite/python/test_checkpoint.py
  testsuite/python/tests_common.py
  testsuite/python/thermalized_bond.py
  testsuite/python/virtual_sites_relative.py
  testsuite/python/virtual_sites_tracers_common.py
  testsuite/python/writevtf.py
Labels: Improvement, Testcase, automerge

#3418 core: Removed MEMBRANE_COLLISION + out_direction
  doc/sphinx/advanced_methods.rst
  doc/sphinx/installation.rst
  doc/sphinx/inter_bonded.rst
  doc/sphinx/inter_non-bonded.rst
  maintainer/configs/maxset.hpp
  samples/object_in_fluid/motivation.py
  src/config/config.hpp
  src/config/features.def
  src/core/CMakeLists.txt
  src/core/Particle.hpp
  src/core/forces_inline.hpp
  src/core/nonbonded_interactions/nonbonded_interaction_data.cpp
  src/core/nonbonded_interactions/nonbonded_interaction_data.hpp
  src/core/object-in-fluid/membrane_collision.cpp
  src/core/object-in-fluid/membrane_collision.hpp
  src/core/object-in-fluid/out_direction.cpp
  src/core/object-in-fluid/out_direction.hpp
  src/core/particle_data.cpp
  src/core/particle_data.hpp
  src/python/espressomd/interactions.pxd
  src/python/espressomd/interactions.pyx
  src/python/espressomd/particle_data.pxd
  src/python/espressomd/particle_data.pyx
  src/python/object_in_fluid/oif_classes.py
  testsuite/python/oif_volume_conservation.py
Labels: automerge

#3424 P3M interpolation cleanup
  src/core/electrostatics_magnetostatics/elc.cpp
  src/core/electrostatics_magnetostatics/p3m-common.cpp
  src/core/electrostatics_magnetostatics/p3m-common.hpp
  src/core/electrostatics_magnetostatics/p3m-dipolar.cpp
  src/core/electrostatics_magnetostatics/p3m.cpp
  src/core/electrostatics_magnetostatics/p3m.hpp
  src/core/electrostatics_magnetostatics/p3m_gpu_cuda.cu
  src/utils/include/utils/math/bspline.hpp
Labels: Core, Improvement, automerge

#3427 Fix Boost tests
  src/core/unit_tests/grid_test.cpp
  src/utils/tests/int_pow_test.cpp
  src/utils/tests/interpolation_test.cpp
  src/utils/tests/matrix_vector_product.cpp
Labels: BugFix, Core, automerge

#3408 Update tutorials and improve tutorial testing framework
  doc/sphinx/electrostatics.rst
  doc/tutorials/01-lennard_jones/01-lennard_jones.ipynb
  doc/tutorials/01-lennard_jones/CMakeLists.txt
  doc/tutorials/04-lattice_boltzmann/04-lattice_boltzmann_part1.ipynb
  doc/tutorials/04-lattice_boltzmann/04-lattice_boltzmann_part4.ipynb
  doc/tutorials/04-lattice_boltzmann/CMakeLists.txt
  doc/tutorials/04-lattice_boltzmann/scripts/04-lattice_boltzmann_part4_solution.py
  doc/tutorials/05-raspberry_electrophoresis/05-raspberry_electrophoresis.ipynb
  doc/tutorials/05-raspberry_electrophoresis/CMakeLists.txt
  doc/tutorials/11-ferrofluid/11-ferrofluid_part1.ipynb
  doc/tutorials/11-ferrofluid/11-ferrofluid_part2.ipynb
  doc/tutorials/11-ferrofluid/11-ferrofluid_part3.ipynb
  doc/tutorials/CMakeLists.txt
  doc/tutorials/html_runner.py
  samples/billiard.py
  samples/chamber_game.py
  samples/espresso_logo.py
  samples/lbf.py
  src/python/espressomd/particle_data.pyx
  testsuite/scripts/importlib_wrapper.py
  testsuite/scripts/test_importlib_wrapper.py
  testsuite/scripts/tutorials/CMakeLists.txt
  testsuite/scripts/tutorials/test_01-lennard_jones.py
  testsuite/scripts/tutorials/test_04-lattice_boltzmann_part4_solution.py
  testsuite/scripts/tutorials/test_05-raspberry_electrophoresis.py
  testsuite/scripts/tutorials/test_html_runner.py
Labels: CMake, Documentation, Improvement, Testcase, automerge

#3432 testsuite: increase error bounds for test of electrophoresis sample.
  testsuite/scripts/samples/test_electrophoresis.py
Labels: automerge

#3428 P3M pressure+dipole term refactoring
  src/core/electrostatics_magnetostatics/coulomb.cpp
  src/core/electrostatics_magnetostatics/elc.cpp
  src/core/electrostatics_magnetostatics/fft.cpp
  src/core/electrostatics_magnetostatics/fft.hpp
  src/core/electrostatics_magnetostatics/p3m-dipolar.cpp
  src/core/electrostatics_magnetostatics/p3m-dipolar.hpp
  src/core/electrostatics_magnetostatics/p3m.cpp
  src/core/electrostatics_magnetostatics/p3m.hpp
  src/core/electrostatics_magnetostatics/p3m_send_mesh.cpp
Labels: Core, Improvement, automerge

#1842 Brownian Dynamics within the existing VV loop
  doc/doxygen/bibliography.bib
  doc/sphinx/analysis.rst
  doc/sphinx/system_setup.rst
  doc/sphinx/zrefs.bib
  maintainer/configs/maxset.hpp
  maintainer/configs/no_rotation.hpp
  src/config/features.def
  src/config/myconfig-default.hpp
  src/core/global.cpp
  src/core/global.hpp
  src/core/integrate.cpp
  src/core/integrate.hpp
  src/core/integrators/brownian_inline.hpp
  src/core/random.hpp
  src/core/rotation.cpp
  src/core/rotation.hpp
  src/core/thermostat.cpp
  src/core/thermostat.hpp
  src/python/espressomd/globals.pxd
  src/python/espressomd/integrate.pxd
  src/python/espressomd/integrate.pyx
  src/python/espressomd/thermostat.pxd
  src/python/espressomd/thermostat.pyx
  testsuite/python/CMakeLists.txt
  testsuite/python/brownian_dynamics.py
  testsuite/python/rotational-diffusion-aniso.py
  testsuite/python/rotational_inertia.py
  testsuite/python/save_checkpoint.py
  testsuite/python/test_checkpoint.py
  testsuite/python/tests_common.py
Labels: Core, Improvement, automerge

#3438 Refactor thermostats and add unit tests
  src/core/forces_inline.hpp
  src/core/global.cpp
  src/core/global.hpp
  src/core/integrate.cpp
  src/core/integrators/brownian_inline.hpp
  src/core/integrators/langevin_inline.hpp
  src/core/integrators/velocity_verlet_npt.cpp
  src/core/rotation.hpp
  src/core/thermostat.cpp
  src/core/thermostat.hpp
  src/core/unit_tests/CMakeLists.txt
  src/core/unit_tests/thermostats_test.cpp
  src/python/espressomd/thermostat.pxd
  src/python/espressomd/thermostat.pyx
  src/script_interface/Globals.hpp
  src/utils/include/utils/Vector.hpp
  src/utils/tests/Vector_test.cpp
Labels: Core, Improvement, Testcase, automerge

#3440 New tuple algorithms
  src/utils/include/utils/tuple.hpp
  src/utils/tests/tuple_test.cpp
Labels: Core, Improvement, automerge

#3441 utility: added inertia tensor calculation at the python level.
  requirements.txt
  samples/rigid_body.py
  src/python/espressomd/rotation.py
  testsuite/python/CMakeLists.txt
  testsuite/python/rotation.py
  testsuite/python/unittest_decorators.py
Labels: automerge

#3443 Bond cutoff
  src/core/bonded_interactions/bonded_interaction_data.cpp
  src/core/bonded_interactions/bonded_interaction_data.hpp
  src/core/bonded_interactions/bonded_tab.cpp
Labels: BugFix, Core, automerge
