Repository espressomd/espresso, pull requests merged in 2020-11, with the labels that each got.

#3983 Ferrofluid tutorial
  doc/tutorials/11-ferrofluid/11-ferrofluid_part1.ipynb
  doc/tutorials/11-ferrofluid/11-ferrofluid_part2.ipynb
  doc/tutorials/11-ferrofluid/11-ferrofluid_part3.ipynb
  doc/tutorials/11-ferrofluid/CMakeLists.txt
  testsuite/scripts/tutorials/test_11-ferrofluid_3.py
Labels: Documentation, automerge

#3984 Simplify CI and bump version requirements
  .gitlab-ci.yml
  .lgtm.yml
  CMakeLists.txt
  doc/sphinx/installation.rst
Labels: DevOps, automerge

#3985 Sort out CUDA builds
  .gitlab-ci.yml
  maintainer/CI/build_cmake.sh
  maintainer/CI/build_docker.sh
Labels: DevOps, automerge

#3986 Make code coverage more verbose
  maintainer/CI/build_cmake.sh
Labels: DevOps, automerge

#3987 Remove GPU implementation of Stokesian Dynamics
  doc/sphinx/installation.rst
  samples/dancing.py
  src/config/features.def
  src/core/CMakeLists.txt
  src/core/stokesian_dynamics/sd_interface.cpp
  src/core/stokesian_dynamics/sd_interface.hpp
  src/core/thermostat.cpp
  src/core/thermostat.hpp
  src/python/espressomd/integrate.pxd
  src/python/espressomd/integrate.pyx
  src/python/espressomd/thermostat.pxd
  src/python/espressomd/thermostat.pyx
  testsuite/python/CMakeLists.txt
  testsuite/python/save_checkpoint.py
  testsuite/python/stokesian_dynamics.py
  testsuite/python/stokesian_dynamics_cpu.py
  testsuite/python/stokesian_dynamics_gpu.py
  testsuite/python/test_checkpoint.py
  testsuite/scripts/samples/CMakeLists.txt
  testsuite/scripts/samples/test_dancing.py
Labels: automerge

#3988 Coverage report of scripts
  .codecov.yml
  .gitlab-ci.yml
  CMakeLists.txt
  maintainer/CI/build_cmake.sh
  src/python/pypresso.cmakein
  testsuite/CMakeLists.txt
  testsuite/python/CMakeLists.txt
  testsuite/scripts/CMakeLists.txt
  testsuite/scripts/benchmarks/CMakeLists.txt
  testsuite/scripts/samples/CMakeLists.txt
  testsuite/scripts/tutorials/CMakeLists.txt
Labels: DevOps, automerge

#3991 Update grand_canonical.py
  samples/grand_canonical.py
Labels: automerge

#3994 Bump Boost version requirement to 1.66
  CMakeLists.txt
  testsuite/python/CMakeLists.txt
  testsuite/scripts/CMakeLists.txt
Labels: BugFix, CMake, automerge

#3996 Interface for standard error of accumulator
  doc/sphinx/analysis.rst
  doc/tutorials/charged_system/charged_system-1.ipynb
  doc/tutorials/lennard_jones/lennard_jones.ipynb
  samples/drude_bmimpf6.py
  samples/electrophoresis.py
  samples/lb_profile.py
  src/core/accumulators/MeanVarianceCalculator.cpp
  src/core/accumulators/MeanVarianceCalculator.hpp
  src/core/reaction_ensemble.cpp
  src/python/espressomd/accumulators.py
  src/script_interface/accumulators/MeanVarianceCalculator.hpp
  src/utils/include/utils/Accumulator.hpp
  src/utils/tests/accumulator.cpp
  testsuite/python/accumulator.py
  testsuite/python/lb_poiseuille_cylinder.py
  testsuite/python/test_checkpoint.py
Labels: ApiChange, automerge

#3997 Simplify ProfileObservable code
  src/core/observables/CylindricalDensityProfile.hpp
  src/core/observables/CylindricalFluxDensityProfile.hpp
  src/core/observables/CylindricalLBFluxDensityProfileAtParticlePositions.cpp
  src/core/observables/CylindricalLBFluxDensityProfileAtParticlePositions.hpp
  src/core/observables/CylindricalLBProfileObservable.hpp
  src/core/observables/CylindricalLBVelocityProfile.cpp
  src/core/observables/CylindricalLBVelocityProfile.hpp
  src/core/observables/CylindricalLBVelocityProfileAtParticlePositions.cpp
  src/core/observables/CylindricalLBVelocityProfileAtParticlePositions.hpp
  src/core/observables/CylindricalPidProfileObservable.hpp
  src/core/observables/CylindricalProfileObservable.hpp
  src/core/observables/CylindricalVelocityProfile.hpp
  src/core/observables/DensityProfile.hpp
  src/core/observables/FluxDensityProfile.hpp
  src/core/observables/ForceDensityProfile.hpp
  src/core/observables/LBProfileObservable.hpp
  src/core/observables/LBVelocityProfile.cpp
  src/core/observables/LBVelocityProfile.hpp
  src/core/observables/PidObservable.cpp
  src/core/observables/PidProfileObservable.hpp
  src/core/observables/ProfileObservable.hpp
  src/script_interface/observables/CylindricalLBProfileObservable.hpp
  src/script_interface/observables/CylindricalPidProfileObservable.hpp
  src/script_interface/observables/LBProfileObservable.hpp
  src/script_interface/observables/PidProfileObservable.hpp
  src/script_interface/observables/ProfileObservable.hpp
  testsuite/python/observable_cylindrical.py
  testsuite/python/observable_cylindricalLB.py
  testsuite/python/observable_profile.py
  testsuite/python/observable_profileLB.py
Labels: CodeQuality, automerge

#3995 Reduce code duplication in thermostat tests
  testsuite/python/CMakeLists.txt
  testsuite/python/brownian_dynamics.py
  testsuite/python/dpd.py
  testsuite/python/langevin_thermostat.py
  testsuite/python/lb_thermostat.py
  testsuite/python/tests_common.py
  testsuite/python/thermalized_bond.py
  testsuite/python/thermostats_common.py
Labels: CodeQuality, automerge

#4000 CI: Pin Python version in mac runners
  .github/workflows/build.yml
Labels: DevOps, automerge

#4002 Make vtk dependency optional
  .github/workflows/build.yml
  src/python/espressomd/visualization_mayavi.pyx
Labels: DevOps, Python, automerge

#3999 New integration tests framework
  .gitlab-ci.yml
  doc/sphinx/advanced_methods.rst
  doc/sphinx/inter_bonded.rst
  doc/sphinx/zrefs.bib
  src/core/Particle.hpp
  src/core/immersed_boundary/ImmersedBoundaries.cpp
  src/core/immersed_boundary/ibm_tribend.cpp
  src/core/immersed_boundary/ibm_tribend.hpp
  src/core/immersed_boundary/ibm_triel.cpp
  src/core/immersed_boundary/ibm_triel.hpp
  src/core/particle_data.cpp
  src/core/particle_data.hpp
  src/core/stokesian_dynamics/sd_interface.cpp
  src/core/thermostats/brownian_inline.hpp
  src/core/thermostats/langevin_inline.hpp
  src/python/espressomd/integrate.pxd
  src/python/espressomd/interactions.pyx
  src/python/espressomd/particle_data.pxd
  src/python/espressomd/particle_data.pyx
  src/python/espressomd/thermostat.pxd
  testsuite/python/CMakeLists.txt
  testsuite/python/accumulator.py
  testsuite/python/accumulator_correlator.py
  testsuite/python/accumulator_mean_variance.py
  testsuite/python/accumulator_time_series.py
  testsuite/python/brownian_dynamics.py
  testsuite/python/brownian_dynamics_stats.py
  testsuite/python/constant_pH.py
  testsuite/python/dpd.py
  testsuite/python/dpd_stats.py
  testsuite/python/elc.py
  testsuite/python/langevin_thermostat.py
  testsuite/python/langevin_thermostat_stats.py
  testsuite/python/lb.py
  testsuite/python/lb_stats.py
  testsuite/python/npt_thermostat.py
  testsuite/python/p3m_electrostatic_pressure.py
  testsuite/python/reaction_ensemble.py
  testsuite/python/stokesian_dynamics.py
  testsuite/python/stokesian_thermostat.py
  testsuite/python/virtual_sites_tracers_common.py
  testsuite/python/wang_landau_reaction_ensemble.py
  testsuite/python/widom_insertion.py
Labels: BugFix, DevOps, Testcase, automerge

#4011 Documentation maintenance
  .gitlab-ci.yml
  src/core/MpiCallbacks.hpp
  src/core/actor/specfunc_cuda.hpp
  src/core/collision.hpp
  src/core/cuda_init_cuda.cu
  src/core/electrostatics_magnetostatics/elc.cpp
  src/core/electrostatics_magnetostatics/fft.cpp
  src/core/electrostatics_magnetostatics/mmm1d.cpp
  src/core/electrostatics_magnetostatics/p3m-dipolar.cpp
  src/core/electrostatics_magnetostatics/p3m.cpp
  src/core/electrostatics_magnetostatics/specfunc.cpp
  src/core/event.hpp
  src/core/ghosts.hpp
  src/core/grid_based_algorithms/halo.hpp
  src/core/grid_based_algorithms/lb.cpp
  src/core/grid_based_algorithms/lb.hpp
  src/core/grid_based_algorithms/lbgpu.hpp
  src/core/grid_based_algorithms/lbgpu_cuda.cu
  src/core/integrate.hpp
  src/core/nonbonded_interactions/nonbonded_interaction_data.hpp
  src/core/npt.hpp
  src/core/rattle.cpp
  src/core/statistics_chain.hpp
  src/core/thermostat.hpp
  src/script_interface/observables/initialize.cpp
  src/utils/include/utils/constants.hpp
  src/utils/include/utils/index.hpp
  src/utils/include/utils/math/vec_rotate.hpp
  src/utils/include/utils/memory.hpp
Labels: CodeQuality, Documentation, automerge

#4010 Some LB cleanup
  src/core/grid_based_algorithms/lb-d3q19.hpp
  src/core/grid_based_algorithms/lb.cpp
Labels: CodeQuality, Core, automerge

#4018 Create installation FAQ
  doc/sphinx/installation.rst
  doc/sphinx/introduction.rst
Labels: Documentation, automerge
