Repository espressomd/espresso, pull requests merged in 2020-09, with the labels that each got.

#3874 Refactor short range loop and cells
  src/core/AtomDecomposition.hpp
  src/core/BoxGeometry.hpp
  src/core/CMakeLists.txt
  src/core/CellStructure.cpp
  src/core/CellStructure.hpp
  src/core/DomainDecomposition.cpp
  src/core/DomainDecomposition.hpp
  src/core/EspressoSystemInterface.hpp
  src/core/ParticleDecomposition.hpp
  src/core/algorithm/for_each_pair.hpp
  src/core/algorithm/link_cell.hpp
  src/core/algorithm/verlet_ia.hpp
  src/core/cells.cpp
  src/core/cells.hpp
  src/core/collision.cpp
  src/core/collision.hpp
  src/core/communication.cpp
  src/core/cuda_common_cuda.cu
  src/core/cuda_init_cuda.cu
  src/core/debug.cpp
  src/core/debug.hpp
  src/core/dpd.cpp
  src/core/electrostatics_magnetostatics/icc.cpp
  src/core/energy.cpp
  src/core/energy_inline.hpp
  src/core/event.cpp
  src/core/forces.cpp
  src/core/forces_inline.hpp
  src/core/grid_based_algorithms/lbgpu_cuda.cu
  src/core/immersed_boundary/ImmersedBoundaries.cpp
  src/core/immersed_boundary/ImmersedBoundaries.hpp
  src/core/integrate.cpp
  src/core/integrate.hpp
  src/core/nonbonded_interactions/nonbonded_interaction_data.cpp
  src/core/object-in-fluid/oif_global_forces.cpp
  src/core/particle_data.cpp
  src/core/particle_data.hpp
  src/core/pressure.cpp
  src/core/pressure_inline.hpp
  src/core/rattle.cpp
  src/core/short_range_loop.hpp
  src/core/unit_tests/CMakeLists.txt
  src/core/unit_tests/link_cell_test.cpp
  src/core/unit_tests/verlet_ia_test.cpp
  src/utils/include/utils/NoOp.hpp
Labels: Core, Improvement, automerge

#3885 Correct second order term for forces in LB
  src/core/grid_based_algorithms/lb.cpp
  src/core/grid_based_algorithms/lbgpu_cuda.cu
Labels: automerge

#3896 Fix Stokesian Dynamics build system
  CMakeLists.txt
Labels: BugFix, CMake, automerge

#3891 Make Steepest Descent a regular integrator
  doc/sphinx/running.rst
  doc/sphinx/system_setup.rst
  doc/tutorials/02-charged_system/02-charged_system-1.ipynb
  doc/tutorials/02-charged_system/02-charged_system-2.ipynb
  doc/tutorials/02-charged_system/scripts/nacl.py
  doc/tutorials/02-charged_system/scripts/nacl_units_confined.py
  doc/tutorials/02-charged_system/scripts/nacl_units_confined_vis.py
  doc/tutorials/04-lattice_boltzmann/04-lattice_boltzmann_part3.ipynb
  doc/tutorials/04-lattice_boltzmann/scripts/04-lattice_boltzmann_part3_solution.py
  doc/tutorials/11-ferrofluid/11-ferrofluid_part1.ipynb
  doc/tutorials/11-ferrofluid/11-ferrofluid_part2.ipynb
  doc/tutorials/11-ferrofluid/11-ferrofluid_part3.ipynb
  doc/tutorials/12-constant_pH/12-constant_pH.ipynb
  maintainer/benchmarks/p3m.py
  samples/chamber_game.py
  samples/drude_bmimpf6.py
  samples/visualization_bonded.py
  samples/visualization_cellsystem.py
  samples/visualization_charged.py
  samples/visualization_elc.py
  samples/visualization_npt.py
  src/core/communication.cpp
  src/core/communication.hpp
  src/core/integrate.cpp
  src/core/integrate.hpp
  src/core/integrators/steepest_descent.cpp
  src/core/integrators/steepest_descent.hpp
  src/python/espressomd/integrate.pxd
  src/python/espressomd/integrate.pyx
  src/python/espressomd/minimize_energy.pyx
  src/python/espressomd/thermostat.pyx
  testsuite/python/CMakeLists.txt
  testsuite/python/collision_detection.py
  testsuite/python/dawaanr-and-dds-gpu.py
  testsuite/python/integrator_exceptions.py
  testsuite/python/integrator_steepest_descent.py
  testsuite/python/save_checkpoint.py
Labels: Core, Documentation, Python, automerge

#3901 P3M/GPU tuning behavior changed to match documentation
  src/core/electrostatics_magnetostatics/p3m.cpp
  src/python/espressomd/electrostatics.pyx
Labels: automerge

#3888 Refactor thermostat infrastructure
  doc/sphinx/system_setup.rst
  src/core/bonded_interactions/thermalized_bond.cpp
  src/core/bonded_interactions/thermalized_bond.hpp
  src/core/communication.cpp
  src/core/constraints/ShapeBasedConstraint.cpp
  src/core/dpd.cpp
  src/core/forces.cpp
  src/core/forces.hpp
  src/core/forces_inline.hpp
  src/core/global.cpp
  src/core/grid_based_algorithms/lb.cpp
  src/core/grid_based_algorithms/lb_particle_coupling.cpp
  src/core/integrate.cpp
  src/core/integrate.hpp
  src/core/integrators/brownian_inline.hpp
  src/core/integrators/stokesian_dynamics_inline.hpp
  src/core/integrators/velocity_verlet_inline.hpp
  src/core/integrators/velocity_verlet_npt.cpp
  src/core/npt.cpp
  src/core/npt.hpp
  src/core/random.hpp
  src/core/stokesian_dynamics/sd_interface.cpp
  src/core/stokesian_dynamics/sd_interface.hpp
  src/core/thermostat.cpp
  src/core/thermostat.hpp
  src/core/thermostats/brownian_inline.hpp
  src/core/thermostats/langevin_inline.hpp
  src/core/thermostats/npt_inline.hpp
  src/core/unit_tests/random_test.cpp
  src/core/unit_tests/random_test.hpp
  src/core/unit_tests/thermostats_test.cpp
  src/python/espressomd/interactions.pxd
  src/python/espressomd/interactions.pyx
  src/python/espressomd/thermostat.pxd
  src/python/espressomd/thermostat.pyx
  src/utils/include/utils/u32_to_u64.hpp
  testsuite/python/brownian_dynamics.py
  testsuite/python/langevin_thermostat.py
  testsuite/python/test_checkpoint.py
  testsuite/scripts/samples/test_electrophoresis.py
Labels: BugFix, Core, Testcase, automerge

#3902 Check tutorial URLs pointing to the user guide
  .gitlab-ci.yml
  doc/tutorials/06-active_matter/06-active_matter.ipynb
  doc/tutorials/07-electrokinetics/07-electrokinetics.ipynb
  maintainer/CI/jupyter_warnings.py
  testsuite/scripts/CMakeLists.txt
  testsuite/scripts/utils/CMakeLists.txt
  testsuite/scripts/utils/test_maintainer_CI_jupyter_warnings.py
Labels: CI, automerge

#3925 P3M: reordered sanity checks in initialization
  src/core/electrostatics_magnetostatics/p3m.cpp
Labels: automerge

#3881 Tutorial 1 - Lennard-Jones
  doc/tutorials/01-lennard_jones/01-lennard_jones.ipynb
  doc/tutorials/01-lennard_jones/NotesForTutor.md
  doc/tutorials/html_runner.py
  testsuite/scripts/tutorials/test_01-lennard_jones.py
  testsuite/scripts/tutorials/test_html_runner.py
Labels: automerge

#3847 Fix regression in CPU LB thermalization.
  src/core/grid_based_algorithms/lb.cpp
  testsuite/python/CMakeLists.txt
  testsuite/python/lb_pressure_tensor.py
  testsuite/python/lb_pressure_tensor_acf.py
Labels: BugFix, Testcase, automerge

#3911 Remove memory allocation on GPU from MPI worker nodes
  src/core/event.cpp
Labels: Core, automerge
