Repository espressomd/espresso, pull requests merged in 2020-10, with the labels that each got.

#3914 tutorial 2: charged rod
  doc/tutorials/02-charged_system/02-charged_system-1.ipynb
  doc/tutorials/02-charged_system/tutor_notes.md
  testsuite/scripts/tutorials/test_02-charged_system-1.py
Labels: automerge

#3927 Tutorial 2: WCA, ELECTROSTATICS feature guard
  doc/tutorials/02-charged_system/02-charged_system-1.ipynb
Labels: automerge

#3929 Tutorial 1: split long exercise
  doc/tutorials/01-lennard_jones/01-lennard_jones.ipynb
  testsuite/scripts/tutorials/test_01-lennard_jones.py
Labels: automerge

#3919 Update Ferrofluid tutorials 1&2 for Espresso summerschool 2020
  doc/tutorials/11-ferrofluid/11-ferrofluid_part1.ipynb
  doc/tutorials/11-ferrofluid/11-ferrofluid_part2.ipynb
  doc/tutorials/11-ferrofluid/NotesForTutor.md
  testsuite/scripts/tutorials/test_11-ferrofluid_1.py
  testsuite/scripts/tutorials/test_11-ferrofluid_2.py
Labels: automerge

#3917 Tutorial 12 - constant-pH
  doc/tutorials/12-constant_pH/12-constant_pH.ipynb
  doc/tutorials/12-constant_pH/NotesForTutor.md
  testsuite/scripts/tutorials/CMakeLists.txt
  testsuite/scripts/tutorials/test_12-constant_pH__ideal.py
  testsuite/scripts/tutorials/test_12-constant_pH__interactions.py
Labels: automerge

#3937 Tutorials typos and tutorial 12 assert_features
  doc/tutorials/01-lennard_jones/01-lennard_jones.ipynb
  doc/tutorials/02-charged_system/02-charged_system-1.ipynb
  doc/tutorials/02-charged_system/CMakeLists.txt
  doc/tutorials/11-ferrofluid/CMakeLists.txt
  doc/tutorials/12-constant_pH/12-constant_pH.ipynb
Labels: automerge

#3893 Tutorial 4 - Lattice-Boltzmann
  doc/tutorials/04-lattice_boltzmann/04-lattice_boltzmann_part1.ipynb
  doc/tutorials/04-lattice_boltzmann/04-lattice_boltzmann_part2.ipynb
  doc/tutorials/04-lattice_boltzmann/04-lattice_boltzmann_part3.ipynb
  doc/tutorials/04-lattice_boltzmann/04-lattice_boltzmann_part4.ipynb
  doc/tutorials/04-lattice_boltzmann/CMakeLists.txt
  doc/tutorials/04-lattice_boltzmann/scripts/04-lattice_boltzmann_part3_solution.py
  doc/tutorials/04-lattice_boltzmann/tutor_notes.md
  src/python/espressomd/lb.pyx
  testsuite/scripts/tutorials/CMakeLists.txt
  testsuite/scripts/tutorials/test_04-lattice_boltzmann_part2.py
  testsuite/scripts/tutorials/test_04-lattice_boltzmann_part3.py
  testsuite/scripts/tutorials/test_04-lattice_boltzmann_part3_solution.py
  testsuite/scripts/tutorials/test_04-lattice_boltzmann_part4.py
Labels: automerge

#3943 Summer school 2020 wrap-up
  Readme.md
  doc/sphinx/installation.rst
  doc/tutorials/02-charged_system/02-charged_system-1.ipynb
  doc/tutorials/04-lattice_boltzmann/04-lattice_boltzmann_part3.ipynb
  doc/tutorials/04-lattice_boltzmann/CMakeLists.txt
  doc/tutorials/11-ferrofluid/11-ferrofluid_part1.ipynb
  doc/tutorials/11-ferrofluid/11-ferrofluid_part2.ipynb
  doc/tutorials/11-ferrofluid/CMakeLists.txt
  doc/tutorials/12-constant_pH/12-constant_pH.ipynb
  testsuite/scripts/tutorials/test_04-lattice_boltzmann_part3.py
Labels: CMake, Documentation, Testcase, automerge

#3887 Rotational code maintenance
  src/core/constraints/ShapeBasedConstraint.cpp
  src/core/electrostatics_magnetostatics/dipole_inline.hpp
  src/core/electrostatics_magnetostatics/p3m-dipolar.hpp
  src/core/forces_inline.hpp
  src/core/nonbonded_interactions/gay_berne.hpp
  src/core/pressure_inline.hpp
  src/core/rotation.cpp
  testsuite/python/CMakeLists.txt
  testsuite/python/rotational_dynamics.py
Labels: Core, Testcase, automerge

#3956 Add pylint configuration to pre-commit.
  .pre-commit-config.yaml
  doc/sphinx/conf.py.in
  maintainer/CI/fix_style.sh
Labels: automerge

#3949 Move HTML tutorials to nightly builds
  .gitlab-ci.yml
  cmake/MyConfig.cmake
  doc/sphinx/README.rst
  doc/sphinx/Readme.rst
  doc/tutorials/02-charged_system/NotesForTutor.md
  doc/tutorials/04-lattice_boltzmann/NotesForTutor.md
  doc/tutorials/11-ferrofluid/11-ferrofluid_part1.ipynb
  doc/tutorials/Readme.rst
  testsuite/scripts/tutorials/test_11-ferrofluid_1.py
Labels: CI, Documentation, automerge

#3957 Add 4.1.4 release notes
  NEWS
  Readme.md
  doc/sphinx/appendix.rst
  doc/sphinx/introduction.rst
  doc/tutorials/01-lennard_jones/01-lennard_jones.ipynb
  doc/tutorials/11-ferrofluid/11-ferrofluid_part2.ipynb
  doc/tutorials/12-constant_pH/12-constant_pH.ipynb
  src/core/cells.hpp
  src/core/electrostatics_magnetostatics/mmm1d.hpp
  src/core/electrostatics_magnetostatics/p3m-dipolar.cpp
  src/core/electrostatics_magnetostatics/p3m.cpp
  src/core/grid_based_algorithms/halo.hpp
  src/core/rattle.cpp
  src/python/espressomd/particle_data.pyx
  src/script_interface/packed_variant.hpp
  testsuite/python/lb_pressure_tensor.py
Labels: automerge

#3966 Remove ROCm integration
  .gitlab-ci.yml
  CMakeLists.txt
  cmake/FindCUDACompilerHIP.cmake
  doc/sphinx/installation.rst
  src/core/CudaDeviceAllocator.hpp
  src/core/CudaHostAllocator.cu
  src/core/EspressoSystemInterface.hpp
  src/core/EspressoSystemInterface_cuda.cu
  src/core/actor/DipolarBarnesHut_cuda.cu
  src/core/actor/DipolarDirectSum_cuda.cu
  src/core/actor/Mmm1dgpuForce_cuda.cu
  src/core/actor/mmm-common_cuda.hpp
  src/core/cuda_common_cuda.cu
  src/core/cuda_init.hpp
  src/core/cuda_init_cuda.cu
  src/core/cuda_interface.hpp
  src/core/cuda_utils.hpp
  src/core/cuda_wrapper.hpp
  src/core/cufft_wrapper.hpp
  src/core/curand_wrapper.hpp
  src/core/electrostatics_magnetostatics/p3m.cpp
  src/core/electrostatics_magnetostatics/p3m_gpu_cuda.cu
  src/core/electrostatics_magnetostatics/p3m_gpu_error_cuda.cu
  src/core/grid_based_algorithms/electrokinetics_cuda.cu
  src/core/grid_based_algorithms/fd-electrostatics.cuh
  src/core/grid_based_algorithms/fd-electrostatics_cuda.cu
  src/core/grid_based_algorithms/lbgpu.cuh
  src/core/grid_based_algorithms/lbgpu_cuda.cu
  src/core/virtual_sites/lb_inertialess_tracers_cuda.cu
  src/utils/include/utils/device_qualifier.hpp
Labels: CI, Core, automerge

#3961 Fix tabulated bond memory leaks
  src/core/CellStructure.hpp
  src/core/Particle.hpp
  src/core/bonded_interactions/bonded_interaction_data.hpp
  src/core/bonded_interactions/bonded_tab.cpp
  src/core/communication.cpp
  src/core/communication.hpp
  src/core/electrostatics_magnetostatics/icc.cpp
  src/core/electrostatics_magnetostatics/p3m.hpp
  src/core/galilei.cpp
  src/core/galilei.hpp
  src/core/io/writer/h5md_core.hpp
  src/core/nonbonded_interactions/nonbonded_interaction_data.cpp
  src/core/nonbonded_interactions/nonbonded_interaction_data.hpp
  src/core/pressure_inline.hpp
Labels: BugFix, Core, automerge

#3965 Readme: Mention ensembles with particle exchange
  Readme.md
Labels: automerge

#3973 Remove 'Current' observable.
  doc/sphinx/analysis.rst
  src/core/observables/Current.hpp
  src/python/espressomd/observables.py
  src/script_interface/observables/initialize.cpp
  testsuite/python/observables.py
Labels: automerge

#3974 Remove HarmonicDumbbell.
  doc/sphinx/inter_bonded.rst
  src/core/bonded_interactions/CMakeLists.txt
  src/core/bonded_interactions/bonded_interaction_data.cpp
  src/core/bonded_interactions/bonded_interaction_data.hpp
  src/core/bonded_interactions/harmonic_dumbbell.cpp
  src/core/bonded_interactions/harmonic_dumbbell.hpp
  src/core/energy_inline.hpp
  src/core/forces_inline.hpp
  src/core/pressure_inline.hpp
  src/python/espressomd/interactions.pxd
  src/python/espressomd/interactions.pyx
  testsuite/python/interactions_bonded_interface.py
Labels: automerge

#3978 Fix LB node interface
  CMakeLists.txt
  src/core/cluster_analysis/ClusterStructure.cpp
  src/core/particle_data.cpp
  src/python/espressomd/lb.pyx
  src/utils/tests/memcpy_archive_test.cpp
  testsuite/python/lb.py
Labels: Python, automerge

#3976 Fix -Wfloat-conversion
  CMakeLists.txt
  src/core/DomainDecomposition.cpp
  src/core/actor/DipolarBarnesHut_cuda.cu
  src/core/actor/DipolarDirectSum.hpp
  src/core/grid.cpp
  src/core/grid_based_algorithms/lb_boundaries.cpp
  src/core/grid_based_algorithms/lb_interface.cpp
  src/core/grid_based_algorithms/lbboundaries/LBBoundary.hpp
  src/python/espressomd/electrostatics.pyx
  src/utils/include/utils/Histogram.hpp
  src/utils/include/utils/checks/charge_neutrality.hpp
  src/utils/include/utils/interpolation/detail/ll_and_dist.hpp
  src/utils/include/utils/sampling.hpp
Labels: Core, automerge
