Repository espressomd/espresso, pull requests merged in 2020-07, with the labels that each got.

#3786 Invitation summer school 2020
  Readme.md
Labels: automerge

#3765 Faster tests
  testsuite/python/brownian_dynamics.py
  testsuite/python/correlation.py
  testsuite/python/dpd.py
  testsuite/python/integrator_npt.py
  testsuite/python/langevin_thermostat.py
  testsuite/python/reaction_ensemble.py
  testsuite/python/thermalized_bond.py
Labels: automerge

#3791 Update samples
  samples/grand_canonical.py
  samples/lb_profile.py
  samples/widom_insertion.py
  testsuite/scripts/samples/CMakeLists.txt
Labels: Documentation, automerge

#3789 add description for VS Code setup
  doc/sphinx/figures/vs-code-settings.png
  doc/sphinx/installation.rst
Labels: automerge

#3792 Update documentation
  Readme.md
  doc/logo/cup.vmd
  doc/logo/generate_animation.sh
  doc/logo/generate_pixmaps.sh
  doc/sphinx/analysis.rst
  doc/sphinx/introduction.rst
  doc/sphinx/lb.rst
  doc/sphinx/particles.rst
  doc/sphinx/zrefs.bib
  doc/tutorials/04-lattice_boltzmann/scripts/04-lattice_boltzmann_part4_solution.py
  doc/tutorials/06-active_matter/exercises/rectification_simulation.py
  doc/tutorials/06-active_matter/solutions/solutions.txt
  samples/gibbs_ensemble_client.py
  samples/gibbs_ensemble_socket.py
  src/core/actor/DipolarBarnesHut_cuda.cu
  src/core/particle_data.cpp
  src/core/rotation.cpp
  src/python/espressomd/accumulators.py
  src/python/espressomd/io/mpiio.py
  src/python/espressomd/polymer.pyx
  testsuite/python/data/mmm1d_data.txt
  testsuite/python/dpd.py
  testsuite/python/lb_interpolation.py
  testsuite/python/polymer_diamond.py
Labels: Documentation, automerge

#3796 Add 4.1.3 release notes
  NEWS
  Readme.md
Labels: Documentation, automerge

#3785 h5md: cleanup.
  doc/sphinx/io.rst
  samples/h5md.py
  src/core/io/writer/CMakeLists.txt
  src/core/io/writer/h5md_core.cpp
  src/core/io/writer/h5md_core.hpp
  src/core/io/writer/h5md_specification.cpp
  src/core/io/writer/h5md_specification.hpp
  src/python/espressomd/io/writer/h5md.py
  src/script_interface/h5md/h5md.cpp
  src/script_interface/h5md/h5md.hpp
  src/script_interface/h5md/initialize.cpp
  testsuite/python/h5md.py
Labels: ApiChange, Core, Improvement, Python, automerge

#3801 mda: extend MDAnalysis plugin by bond information.
  samples/MDAnalysisIntegration.py
  src/python/espressomd/MDA_ESP/__init__.py
  testsuite/python/CMakeLists.txt
  testsuite/python/mdanalysis.py
  testsuite/scripts/samples/test_MDAnalysisIntegration.py
Labels: Python, Testcase, automerge

#3802 testsuite: Increase number of samples for npt integration test
  testsuite/python/integrator_npt.py
Labels: Testcase, automerge

#3790 Stokesian Dynamics
  .gitlab-ci.yml
  AUTHORS
  CMakeLists.txt
  cmake/cmake_config.cmakein
  doc/doxygen/bibliography.bib
  doc/sphinx/installation.rst
  doc/sphinx/introduction.rst
  doc/sphinx/running.rst
  doc/sphinx/system_setup.rst
  doc/sphinx/zrefs.bib
  libs/CMakeLists.txt
  maintainer/CI/build_cmake.sh
  pylint.log
  samples/dancing.py
  src/config/features.def
  src/core/CMakeLists.txt
  src/core/communication.cpp
  src/core/event.cpp
  src/core/integrate.cpp
  src/core/integrate.hpp
  src/core/integrators/stokesian_dynamics_inline.hpp
  src/core/serialization/SD_particle_data.hpp
  src/core/stokesian_dynamics/CMakeLists.txt
  src/core/stokesian_dynamics/sd_interface.cpp
  src/core/stokesian_dynamics/sd_interface.hpp
  src/core/thermostat.hpp
  src/core/unit_tests/reaction_ensemble_utils_test.cpp
  src/python/espressomd/globals.pyx
  src/python/espressomd/integrate.pxd
  src/python/espressomd/integrate.pyx
  src/python/espressomd/thermostat.pxd
  src/python/espressomd/thermostat.pyx
  testsuite/python/CMakeLists.txt
  testsuite/python/data/dancing.txt
  testsuite/python/save_checkpoint.py
  testsuite/python/stokesian_dynamics.py
  testsuite/python/stokesian_dynamics_cpu.py
  testsuite/python/stokesian_dynamics_gpu.py
  testsuite/python/test_checkpoint.py
  testsuite/scripts/samples/CMakeLists.txt
  testsuite/scripts/samples/test_dancing.py
Labels: ApiChange, New Feature, automerge

#3808 Remove unintentionally added log file
  .gitignore
  pylint.log
Labels: automerge

#3809 maintainer: coverage for integration tests.
  .codecov.yml
  .coveragerc
  .gitlab-ci.yml
  maintainer/CI/build_cmake.sh
  src/python/pypresso.cmakein
  testsuite/python/CMakeLists.txt
Labels: automerge

#3822 testsuite: do not randomize seeds by default in sample tests.
  testsuite/scripts/importlib_wrapper.py
Labels: automerge

#3823 MPI init cleanup
  src/core/communication.cpp
  src/core/communication.hpp
  src/python/espressomd/_init.pyx
  src/python/espressomd/boost.pxd
  src/python/espressomd/communication.pxd
Labels: Core, Improvement, automerge

#3821 testsuite: make electrophoresis sample test deterministic.
  samples/electrophoresis.py
  testsuite/scripts/samples/test_electrophoresis.py
Labels: automerge

#3824 script_interface: Fixed build with c++17
  src/script_interface/accumulators/Correlator.hpp
Labels: Core, Improvement, automerge

#3825 Tutorial 06 active matter update
  doc/tutorials/06-active_matter/06-active_matter.ipynb
  doc/tutorials/06-active_matter/CMakeLists.txt
  doc/tutorials/06-active_matter/exercises/rectification_geometry.py
  doc/tutorials/06-active_matter/exercises/rectification_simulation.py
  doc/tutorials/06-active_matter/figures/rectify.jpg
  doc/tutorials/06-active_matter/figures/rectify.pdf
  doc/tutorials/06-active_matter/figures/rectify.svg
  doc/tutorials/06-active_matter/solutions/rectification_geometry.py
  doc/tutorials/06-active_matter/solutions/rectification_simulation.py
  doc/tutorials/06-active_matter/solutions/solutions.txt
  testsuite/scripts/tutorials/CMakeLists.txt
  testsuite/scripts/tutorials/test_06-active_matter__rectification_geometry.py
Labels: Documentation, automerge

#3827 maintainer: perform mac jobs on github.
  .github/workflows/build.yml
  doc/sphinx/installation.rst
Labels: CI, automerge

#3830 Fix CMake warning, update macOS installation instructions
  .github/workflows/build.yml
  CMakeLists.txt
  doc/sphinx/installation.rst
Labels: CI, Documentation, automerge

#3832 h5md: do not use generator expression in order to not trigger rebuild.
  src/core/io/writer/CMakeLists.txt
Labels: CMake, automerge

#3831 Test: add test for lb pressure tensor acf against viscosity
  testsuite/python/CMakeLists.txt
  testsuite/python/lb_pressure_tensor_acf.py
Labels: automerge

#3835 core: Removed globals derived from the time step
  src/core/communication.cpp
  src/core/integrate.cpp
  src/core/integrate.hpp
  src/core/rotation.cpp
Labels: automerge

#3837 Disable SD GPU feature
  CMakeLists.txt
  cmake/cmake_config.cmakein
  testsuite/python/CMakeLists.txt
Labels: automerge

#3838 SD interface cleanup
  src/core/integrators/stokesian_dynamics_inline.hpp
  src/core/serialization/SD_particle_data.hpp
  src/core/stokesian_dynamics/sd_interface.cpp
  src/core/stokesian_dynamics/sd_interface.hpp
Labels: Core, Improvement, automerge

#3839 Explain notation convention in Gay-Berne formula
  doc/doxygen/bibliography.bib
  doc/sphinx/inter_non-bonded.rst
  doc/sphinx/zrefs.bib
  src/core/nonbonded_interactions/gay_berne.hpp
Labels: Documentation, Improvement, automerge

#3841 P3M generic influence function
  src/core/electrostatics_magnetostatics/p3m.cpp
  src/core/electrostatics_magnetostatics/p3m.hpp
  src/core/electrostatics_magnetostatics/p3m_influence_function.hpp
Labels: Core, Improvement, automerge
