Repository espressomd/espresso, pull requests merged in 2021-04, with the labels that each got.

#4195 Implement slicing for LB
  doc/sphinx/lb.rst
  src/python/espressomd/lb.pyx
  src/python/espressomd/particle_data.pyx
  testsuite/python/CMakeLists.txt
  testsuite/python/lb_slice.py
Labels: ApiChange, Improvement, New Feature, Python, automerge

#4196 Reorganize Reaction Ensemble
  src/core/CMakeLists.txt
  src/core/reaction_ensemble.hpp
  src/core/reaction_methods/CMakeLists.txt
  src/core/reaction_methods/ConstantpHEnsemble.cpp
  src/core/reaction_methods/ConstantpHEnsemble.hpp
  src/core/reaction_methods/ReactionAlgorithm.cpp
  src/core/reaction_methods/ReactionAlgorithm.hpp
  src/core/reaction_methods/ReactionEnsemble.cpp
  src/core/reaction_methods/ReactionEnsemble.hpp
  src/core/reaction_methods/SingleReaction.hpp
  src/core/reaction_methods/WangLandauReactionEnsemble.cpp
  src/core/reaction_methods/WangLandauReactionEnsemble.hpp
  src/core/reaction_methods/WidomInsertion.cpp
  src/core/reaction_methods/WidomInsertion.hpp
  src/core/reaction_methods/tests/CMakeLists.txt
  src/core/reaction_methods/tests/ConstantpHEnsemble_test.cpp
  src/core/reaction_methods/tests/ParticleFactory.hpp
  src/core/reaction_methods/tests/ReactionAlgorithm_test.cpp
  src/core/reaction_methods/tests/ReactionEnsemble_test.cpp
  src/core/reaction_methods/tests/SingleReaction_test.cpp
  src/core/reaction_methods/tests/WangLandauReactionEnsemble_test.cpp
  src/core/reaction_methods/tests/particle_tracking_test.cpp
  src/core/reaction_methods/tests/reaction_methods_utils_test.cpp
  src/core/reaction_methods/utils.cpp
  src/core/reaction_methods/utils.hpp
  src/core/unit_tests/CMakeLists.txt
  src/core/unit_tests/reaction_ensemble_classes_test.cpp
  src/python/espressomd/reaction_ensemble.pxd
  src/python/espressomd/reaction_ensemble.pyx
Labels: Core, automerge

#4206 observables: make ids of ID based observable readonly.
  src/core/observables/PidObservable.hpp
  src/script_interface/observables/CylindricalPidProfileObservable.hpp
  src/script_interface/observables/PidObservable.hpp
  src/script_interface/observables/PidProfileObservable.hpp
  testsuite/python/observable_cylindrical.py
  testsuite/python/observable_profile.py
  testsuite/python/observables.py
Labels: ApiChange, automerge

#4179 Hollowconical Frustum with cutout
  doc/sphinx/constraints.rst
  doc/sphinx/figures/shape-hollowconicalfrustum_central_angle.png
  doc/tutorials/active_matter/exercises/rectification_geometry.py
  doc/tutorials/active_matter/exercises/rectification_simulation.py
  doc/tutorials/active_matter/solutions/rectification_geometry.py
  doc/tutorials/active_matter/solutions/rectification_simulation.py
  samples/visualization_constraints.py
  src/python/espressomd/math.py
  src/python/espressomd/shapes.py
  src/python/espressomd/visualization_opengl.py
  src/script_interface/CylindricalTransformationParameters.hpp
  src/script_interface/shapes/HollowConicalFrustum.hpp
  src/shapes/include/shapes/HollowConicalFrustum.hpp
  src/shapes/src/HollowConicalFrustum.cpp
  src/shapes/unit_tests/HollowConicalFrustum_test.cpp
  src/utils/include/utils/math/cylindrical_transformation_parameters.hpp
  testsuite/python/constraint_shape_based.py
  testsuite/python/es_math.py
Labels: automerge

#4202 core: Avoid some redudant lookups in the particle type map
  src/core/particle_data.cpp
Labels: automerge

#4203 add ext_force_density to ekin
  doc/sphinx/advanced_methods.rst
  src/core/grid_based_algorithms/electrokinetics.hpp
  src/core/grid_based_algorithms/electrokinetics_cuda.cu
  src/python/espressomd/electrokinetics.pxd
  src/python/espressomd/electrokinetics.pyx
  testsuite/python/lb_poiseuille.py
Labels: Python, automerge

#4199 Remove code duplication in non-bonded interactions test
  testsuite/python/constraint_shape_based.py
  testsuite/python/interactions_non-bonded.py
  testsuite/python/tests_common.py
Labels: CodeQuality, Testcase, automerge

#4205 Refactor and test Structure Factor
  src/core/statistics.cpp
  src/core/statistics.hpp
  src/python/espressomd/analyze.pxd
  src/python/espressomd/analyze.pyx
  testsuite/python/CMakeLists.txt
  testsuite/python/sf_simple_lattice.py
Labels: BugFix, CodeQuality, Core, Testcase, automerge

#4211 observables: make observables immutable.
  .gitignore
  src/core/accumulators/MeanVarianceCalculator.hpp
  src/core/observables/CylindricalDensityProfile.hpp
  src/core/observables/CylindricalFluxDensityProfile.hpp
  src/core/observables/CylindricalLBFluxDensityProfileAtParticlePositions.cpp
  src/core/observables/CylindricalLBFluxDensityProfileAtParticlePositions.hpp
  src/core/observables/CylindricalLBProfileObservable.hpp
  src/core/observables/CylindricalLBVelocityProfile.cpp
  src/core/observables/CylindricalLBVelocityProfile.hpp
  src/core/observables/CylindricalLBVelocityProfileAtParticlePositions.cpp
  src/core/observables/CylindricalLBVelocityProfileAtParticlePositions.hpp
  src/core/observables/CylindricalVelocityProfile.hpp
  src/core/observables/DensityProfile.hpp
  src/core/observables/FluxDensityProfile.hpp
  src/core/observables/ForceDensityProfile.hpp
  src/core/observables/LBProfileObservable.hpp
  src/core/observables/LBVelocityProfile.cpp
  src/core/observables/LBVelocityProfile.hpp
  src/core/observables/ProfileObservable.hpp
  src/script_interface/CylindricalTransformationParameters.hpp
  src/script_interface/observables/CylindricalLBProfileObservable.hpp
  src/script_interface/observables/CylindricalPidProfileObservable.hpp
  src/script_interface/observables/LBProfileObservable.hpp
  src/script_interface/observables/PidProfileObservable.hpp
  src/script_interface/observables/RDF.hpp
  testsuite/python/observable_cylindrical.py
  testsuite/python/observable_cylindricalLB.py
  testsuite/python/observable_profile.py
  testsuite/python/observable_profileLB.py
  testsuite/python/rdf.py
Labels: ApiChange, ScriptInterface, automerge

#4198 core: Consider rotational kinetic energy of virtual particles.
  src/core/energy_inline.hpp
  src/core/unit_tests/CMakeLists.txt
  src/core/unit_tests/energy_test.cpp
Labels: automerge

#4218 Non-P3M Coulomb methods maintenance
  doc/doxygen/bibliography.bib
  doc/sphinx/electrostatics.rst
  doc/sphinx/zrefs.bib
  src/core/electrostatics_magnetostatics/coulomb.cpp
  src/core/electrostatics_magnetostatics/debye_hueckel.cpp
  src/core/electrostatics_magnetostatics/debye_hueckel.hpp
  src/core/electrostatics_magnetostatics/reaction_field.cpp
  src/core/electrostatics_magnetostatics/reaction_field.hpp
  src/python/espressomd/electrostatics.pxd
  src/python/espressomd/electrostatics.pyx
  testsuite/python/electrostaticInteractions.py
Labels: BugFix, CodeQuality, Documentation, Testcase, automerge

#4223 Coding day wrap up
  AUTHORS
  Readme.md
  doc/sphinx/electrostatics.rst
  doc/tutorials/lennard_jones/NotesForTutor.md
  samples/gibbs_ensemble_socket.py
  src/core/bonded_interactions/bonded_interactions.dox
  src/core/reaction_methods/WangLandauReactionEnsemble.cpp
  src/python/espressomd/constraints.py
  src/script_interface/ObjectList.hpp
  src/utils/include/utils/matrix.hpp
  testsuite/python/es_math.py
  testsuite/python/interactions_non-bonded.py
  testsuite/python/sf_simple_lattice.py
Labels: automerge

#4228 make ElectrokineticsRoutines inherit from LBFluidRoutines
  doc/sphinx/advanced_methods.rst
  doc/tutorials/electrokinetics/electrokinetics.ipynb
  src/core/grid_based_algorithms/electrokinetics.hpp
  src/core/grid_based_algorithms/electrokinetics_cuda.cu
  src/python/espressomd/electrokinetics.pxd
  src/python/espressomd/electrokinetics.pyx
  src/python/espressomd/lb.pxd
  src/python/espressomd/lb.pyx
  testsuite/python/ek_common.py
  testsuite/python/ek_eof_one_species.py
Labels: ApiChange, BugFix, Python, automerge

#4226 Remove numerical particle ID from samples and user guide
  doc/sphinx/installation.rst
  doc/sphinx/inter_bonded.rst
  doc/sphinx/particles.rst
  samples/MDAnalysisIntegration.py
  samples/billiard.py
  samples/chamber_game.py
  samples/constraints.py
  samples/diffusion_coefficient.py
  samples/electrophoresis.py
  samples/espresso_logo.py
  samples/gibbs_ensemble_client.py
  samples/lbf.py
  samples/minimal-charged-particles.py
  samples/observables_correlators.py
  samples/save_checkpoint.py
  samples/visualization_npt.py
  samples/wang_landau_reaction_ensemble.py
Labels: Documentation, automerge

#4229 CI: Disable deploy stage
  .gitlab-ci.yml
Labels: DevOps, automerge

#4231 Refactor ELC core setter
  src/core/electrostatics_magnetostatics/coulomb.cpp
  src/core/electrostatics_magnetostatics/coulomb.hpp
  src/core/electrostatics_magnetostatics/elc.cpp
  src/core/electrostatics_magnetostatics/elc.hpp
  src/python/espressomd/electrostatics.pxd
  src/python/espressomd/electrostatics.pyx
  testsuite/python/p3m_tuning_exceptions.py
Labels: BugFix, Core, automerge

#4232 Unit test ESPResSo simulations
  src/core/CMakeLists.txt
  src/core/EspressoSystemStandAlone.cpp
  src/core/EspressoSystemStandAlone.hpp
  src/core/communication.cpp
  src/core/communication.hpp
  src/core/particle_data.cpp
  src/core/particle_data.hpp
  src/core/reaction_methods/ReactionAlgorithm.cpp
  src/core/reaction_methods/tests/WangLandauReactionEnsemble_test.cpp
  src/core/reaction_methods/tests/particle_tracking_test.cpp
  src/core/unit_tests/CMakeLists.txt
  src/core/unit_tests/EspressoSystemStandAlone_test.cpp
  src/core/unit_tests/ParticleFactory.hpp
  src/python/espressomd/interactions.pxd
  src/python/espressomd/interactions.pyx
  src/python/espressomd/particle_data.pxd
  src/python/espressomd/particle_data.pyx
Labels: Core, Testcase, automerge

#4227 Test C++17 build
  .gitlab-ci.yml
  CMakeLists.txt
  maintainer/CI/build_cmake.sh
  src/utils/tests/tuple_test.cpp
Labels: DevOps, automerge

#4233 Cleanup non-bonded interaction kernels
  src/core/nonbonded_interactions/bmhtf-nacl.hpp
  src/core/nonbonded_interactions/buckingham.cpp
  src/core/nonbonded_interactions/buckingham.hpp
  src/core/nonbonded_interactions/gaussian.hpp
  src/core/nonbonded_interactions/hat.hpp
  src/core/nonbonded_interactions/hertzian.hpp
  src/core/nonbonded_interactions/lj.hpp
  src/core/nonbonded_interactions/ljcos.cpp
  src/core/nonbonded_interactions/ljcos.hpp
  src/core/nonbonded_interactions/ljcos2.hpp
  src/core/nonbonded_interactions/ljgen.hpp
  src/core/nonbonded_interactions/morse.hpp
  src/core/nonbonded_interactions/nonbonded_tab.hpp
  src/core/nonbonded_interactions/smooth_step.hpp
  src/core/nonbonded_interactions/soft_sphere.hpp
  src/core/nonbonded_interactions/wca.hpp
  src/utils/include/utils/constants.hpp
  testsuite/python/interactions_non-bonded.py
Labels: CodeQuality, Core, automerge

#4234 Script interface maintenance
  src/script_interface/cluster_analysis/Cluster.hpp
  src/script_interface/cluster_analysis/ClusterStructure.hpp
  src/script_interface/tests/get_value_test.cpp
  testsuite/python/cluster_analysis.py
  testsuite/python/constraint_shape_based.py
  testsuite/python/observable_cylindricalLB.py
Labels: ApiChange, Testcase, automerge

#4235 BoxGeometry members private
  src/core/BoxGeometry.hpp
  src/core/EspressoSystemStandAlone.cpp
  src/core/event.cpp
  src/core/event.hpp
  src/core/global.cpp
  src/core/global.hpp
  src/core/grid.cpp
  src/core/grid.hpp
  src/core/integrators/velocity_verlet_npt.cpp
  src/python/espressomd/globals.pxd
  src/python/espressomd/globals.pyx
  testsuite/python/CMakeLists.txt
  testsuite/python/box_geometry.py
Labels: CodeQuality, Core, automerge

#4236 get_mi_... functions as members of BoxGeometry
  src/core/BoxGeometry.hpp
  src/core/CellStructure.hpp
  src/core/DomainDecomposition.cpp
  src/core/bonded_interactions/angle_common.hpp
  src/core/bonded_interactions/dihedral.hpp
  src/core/cluster_analysis/Cluster.cpp
  src/core/collision.cpp
  src/core/electrostatics_magnetostatics/elc.cpp
  src/core/electrostatics_magnetostatics/magnetic_non_p3m_methods.cpp
  src/core/energy_inline.hpp
  src/core/forces_inline.hpp
  src/core/immersed_boundary/ImmersedBoundaries.cpp
  src/core/immersed_boundary/ibm_tribend.cpp
  src/core/immersed_boundary/ibm_triel.cpp
  src/core/object-in-fluid/oif_global_forces.cpp
  src/core/object-in-fluid/oif_local_forces.hpp
  src/core/observables/BondAngles.hpp
  src/core/observables/BondDihedrals.hpp
  src/core/observables/CosPersistenceAngles.hpp
  src/core/observables/ParticleDistances.hpp
  src/core/observables/RDF.cpp
  src/core/pair_criteria/pair_criteria.hpp
  src/core/polymer.cpp
  src/core/pressure_inline.hpp
  src/core/rattle.cpp
  src/core/statistics.cpp
  src/core/unit_tests/BoxGeometry_test.cpp
  src/core/unit_tests/grid_test.cpp
  src/core/virtual_sites.cpp
  src/core/virtual_sites/VirtualSitesRelative.cpp
  src/python/espressomd/grid.pxd
  src/python/espressomd/system.pyx
  src/python/espressomd/visualization_mayavi.pyx
Labels: Core, automerge

#4238 Refactor DLC/DAWAANR/MDDS core setters
  src/core/electrostatics_magnetostatics/dipole.cpp
  src/core/electrostatics_magnetostatics/dipole.hpp
  src/core/electrostatics_magnetostatics/magnetic_non_p3m_methods.cpp
  src/core/electrostatics_magnetostatics/magnetic_non_p3m_methods.hpp
  src/core/electrostatics_magnetostatics/mdlc_correction.cpp
  src/core/electrostatics_magnetostatics/mdlc_correction.hpp
  src/python/espressomd/electrostatic_extensions.pxd
  src/python/espressomd/electrostatic_extensions.pyx
  src/python/espressomd/magnetostatic_extensions.pxd
  src/python/espressomd/magnetostatic_extensions.pyx
  src/python/espressomd/magnetostatics.pxd
  src/python/espressomd/magnetostatics.pyx
  testsuite/python/CMakeLists.txt
  testsuite/python/dipolar_interface.py
  testsuite/python/dipolar_mpi_exceptions.py
  testsuite/python/p3m_tuning_exceptions.py
  testsuite/python/scafacos_interface.py
Labels: CodeQuality, Core, Testcase, automerge
