Repository espressomd/espresso, pull requests merged in 2021-03, with the labels that each got.

#4121 Script interface maintenance
  src/core/RuntimeErrorStream.cpp
  src/python/espressomd/actors.pyx
  src/python/espressomd/constraints.py
  src/python/espressomd/script_interface.pyx
  src/python/espressomd/visualization_opengl.py
  src/script_interface/Variant.hpp
  src/script_interface/constraints/couplings.hpp
  src/script_interface/get_value.hpp
  src/script_interface/packed_variant.hpp
  src/shapes/unit_tests/CMakeLists.txt
  src/shapes/unit_tests/NoWhere_test.cpp
  testsuite/python/constraint_shape_based.py
  testsuite/python/elc.py
  testsuite/python/field_test.py
  testsuite/python/save_checkpoint.py
  testsuite/python/shapes.py
  testsuite/python/test_checkpoint.py
Labels: ApiChange, BugFix, ScriptInterface, Testcase, automerge

#4125 Make ELC an actor
  doc/sphinx/electrostatics.rst
  samples/visualization_elc.py
  src/core/electrostatics_magnetostatics/elc.cpp
  src/core/electrostatics_magnetostatics/p3m-common.cpp
  src/core/electrostatics_magnetostatics/p3m-common.hpp
  src/core/electrostatics_magnetostatics/p3m-dipolar.cpp
  src/core/electrostatics_magnetostatics/p3m.cpp
  src/python/espressomd/electrostatic_extensions.pxd
  src/python/espressomd/electrostatic_extensions.pyx
  src/python/espressomd/electrostatics.pxd
  src/python/espressomd/electrostatics.pyx
  src/python/espressomd/magnetostatic_extensions.pyx
  src/python/espressomd/magnetostatics.pyx
  src/python/espressomd/p3m_common.pxd
  testsuite/python/CMakeLists.txt
  testsuite/python/coulomb_mixed_periodicity.py
  testsuite/python/elc.py
  testsuite/python/elc_vs_analytic.py
  testsuite/python/p3m_tuning_exceptions.py
  testsuite/python/save_checkpoint.py
  testsuite/python/test_checkpoint.py
Labels: ApiChange, Core, Documentation, Python, Testcase, automerge

#4130 Fix Union shape
  .github/actions/build_and_check/action.yml
  .github/workflows/push_pull.yml
  src/script_interface/shapes/Union.hpp
Labels: BugFix, DevOps, automerge

#4135 Fix rare failures in CI
  testsuite/python/coulomb_cloud_wall.py
  testsuite/python/save_checkpoint.py
  testsuite/python/scafacos_interface.py
  testsuite/python/test_checkpoint.py
  testsuite/scripts/tutorials/test_active_matter__rectification_simulation.py
Labels: Testcase, automerge

#4129 Rattle maintenance
  src/core/Particle.hpp
  src/core/rattle.cpp
  src/core/rattle.hpp
  src/python/espressomd/particle_data.pyx
Labels: Core, Documentation, automerge

#4138 Script interface maintenance
  src/python/espressomd/observables.py
  src/python/espressomd/script_interface.pyx
  src/script_interface/Variant.hpp
Labels: Documentation, Python, ScriptInterface, automerge

#4136 Core: Skip ibm bond loop if no ibm objects
  src/core/immersed_boundary/ImmersedBoundaries.cpp
  src/core/immersed_boundary/ImmersedBoundaries.hpp
Labels: automerge

#4148 maintainer: run step if case of failing pipeline.
  .github/workflows/push_pull.yml
Labels: DevOps, automerge

#4152 Refactor cylindrical coordinates transformation and dependent observables
  doc/sphinx/analysis.rst
  doc/tutorials/charged_system/charged_system-1.ipynb
  samples/lb_profile.py
  src/core/grid_based_algorithms/lb_collective_interface.cpp
  src/core/grid_based_algorithms/lb_collective_interface.hpp
  src/core/grid_based_algorithms/lb_interface.cpp
  src/core/grid_based_algorithms/lb_interface.hpp
  src/core/grid_based_algorithms/lb_interpolation.cpp
  src/core/grid_based_algorithms/lb_interpolation.hpp
  src/core/observables/CylindricalDensityProfile.hpp
  src/core/observables/CylindricalFluxDensityProfile.hpp
  src/core/observables/CylindricalLBFluxDensityProfileAtParticlePositions.cpp
  src/core/observables/CylindricalLBProfileObservable.hpp
  src/core/observables/CylindricalLBVelocityProfile.cpp
  src/core/observables/CylindricalLBVelocityProfileAtParticlePositions.cpp
  src/core/observables/CylindricalPidProfileObservable.hpp
  src/core/observables/CylindricalProfileObservable.hpp
  src/core/observables/CylindricalVelocityProfile.hpp
  src/python/espressomd/math.py
  src/python/espressomd/observables.py
  src/script_interface/CylindricalTransformationParameters.hpp
  src/script_interface/initialize.cpp
  src/script_interface/observables/CylindricalLBProfileObservable.hpp
  src/script_interface/observables/CylindricalPidProfileObservable.hpp
  src/shapes/include/shapes/HollowConicalFrustum.hpp
  src/shapes/src/HollowConicalFrustum.cpp
  src/utils/include/utils/math/coordinate_transformation.hpp
  src/utils/include/utils/math/cylindrical_transformation_parameters.hpp
  src/utils/include/utils/math/orthonormal_vec.hpp
  src/utils/include/utils/math/vec_rotate.hpp
  src/utils/tests/CMakeLists.txt
  src/utils/tests/coordinate_transformation.cpp
  src/utils/tests/matrix_test.cpp
  src/utils/tests/orthonormal_vec_test.cpp
  src/utils/tests/vec_rotate_test.cpp
  testsuite/python/lb_poiseuille_cylinder.py
  testsuite/python/observable_cylindrical.py
  testsuite/python/observable_cylindricalLB.py
  testsuite/python/tests_common.py
Labels: Core, Improvement, ScriptInterface, automerge

#4153 Reduce code complexity
  src/core/dpd.cpp
  src/core/dpd.hpp
  src/core/electrostatics_magnetostatics/magnetic_non_p3m_methods.cpp
  src/core/grid_based_algorithms/electrokinetics_cuda.cu
  src/core/particle_data.cpp
  src/core/particle_data.hpp
  src/core/stokesian_dynamics/sd_interface.cpp
  src/core/stokesian_dynamics/sd_interface.hpp
  src/python/espressomd/integrate.pxd
  src/python/espressomd/particle_data.pxd
  testsuite/python/dawaanr-and-bh-gpu.py
  testsuite/python/dawaanr-and-dds-gpu.py
  testsuite/python/dds-and-bh-gpu.py
  testsuite/python/dipolar_direct_summation.py
  testsuite/python/dipolar_interface.py
  testsuite/python/engine_langevin.py
  testsuite/python/observable_cylindrical.py
  testsuite/python/observable_cylindricalLB.py
  testsuite/python/p3m_fft.py
  testsuite/python/tests_common.py
Labels: CodeQuality, Core, Python, automerge

#4159 LB GPU cleanup
  src/core/grid_based_algorithms/electrokinetics_cuda.cu
  src/core/grid_based_algorithms/lbgpu.cpp
  src/core/grid_based_algorithms/lbgpu.cuh
  src/core/grid_based_algorithms/lbgpu.hpp
  src/core/grid_based_algorithms/lbgpu_cuda.cu
  src/core/virtual_sites/lb_inertialess_tracers_cuda.cu
Labels: automerge

#4162 ICC maintenance
  src/core/electrostatics_magnetostatics/coulomb.cpp
  src/core/electrostatics_magnetostatics/coulomb.hpp
  src/core/electrostatics_magnetostatics/icc.cpp
  src/core/electrostatics_magnetostatics/icc.hpp
  src/core/forces.cpp
  src/python/espressomd/electrostatic_extensions.pxd
  src/python/espressomd/electrostatic_extensions.pyx
  src/python/espressomd/utils.pxd
  src/python/espressomd/utils.pyx
  testsuite/python/icc.py
Labels: automerge

#4160 Fix rare failures in CI
  testsuite/python/coulomb_cloud_wall.py
  testsuite/python/dipolar_direct_summation.py
  testsuite/python/save_checkpoint.py
  testsuite/python/scafacos_interface.py
  testsuite/python/test_checkpoint.py
  testsuite/scripts/tutorials/test_raspberry_electrophoresis.py
Labels: DevOps, Testcase, automerge

#4166 fix clang-tidy-10 not recognized
  cmake/FindClangTidy.cmake
Labels: CMake, automerge

#4167 script_interface: Moved serialization for ObjectList from cython to C++
  src/python/espressomd/script_interface.pyx
  src/python/espressomd/shapes.py
  src/script_interface/ObjectHandle.hpp
  src/script_interface/ObjectList.hpp
  src/script_interface/shapes/Union.hpp
  src/script_interface/tests/CMakeLists.txt
  src/script_interface/tests/ObjectList_test.cpp
Labels: ScriptInterface, automerge

#4164 Reaction Ensemble refactor and unit testing
  doc/sphinx/advanced_methods.rst
  src/core/reaction_ensemble.cpp
  src/core/reaction_ensemble.hpp
  src/core/unit_tests/CMakeLists.txt
  src/core/unit_tests/reaction_ensemble_classes_test.cpp
  src/core/unit_tests/reaction_ensemble_utils_test.cpp
  src/python/espressomd/reaction_ensemble.pxd
  src/python/espressomd/reaction_ensemble.pyx
  testsuite/python/CMakeLists.txt
  testsuite/python/constant_pH.py
  testsuite/python/constant_pH_stats.py
  testsuite/python/reaction_ensemble.py
  testsuite/python/wang_landau.py
  testsuite/python/wang_landau_stats.py
Labels: CodeQuality, Core, Testcase, automerge

#4175 Document matrix and quaternion types in utils.
  src/utils/include/utils/matrix.hpp
  src/utils/include/utils/quaternion.hpp
Labels: automerge

#4176 Remove Tutorial Numbers
  doc/tutorials/active_matter/active_matter.ipynb
  doc/tutorials/charged_system/CMakeLists.txt
  doc/tutorials/charged_system/charged_system.ipynb
  doc/tutorials/constant_pH/constant_pH.ipynb
  doc/tutorials/electrokinetics/electrokinetics.ipynb
  doc/tutorials/ferrofluid/ferrofluid_part1.ipynb
  doc/tutorials/ferrofluid/ferrofluid_part2.ipynb
  doc/tutorials/ferrofluid/ferrofluid_part3.ipynb
  doc/tutorials/lattice_boltzmann/lattice_boltzmann_part1.ipynb
  doc/tutorials/lattice_boltzmann/lattice_boltzmann_part2.ipynb
  doc/tutorials/lattice_boltzmann/lattice_boltzmann_part3.ipynb
  doc/tutorials/lattice_boltzmann/lattice_boltzmann_part4.ipynb
  doc/tutorials/lennard_jones/lennard_jones.ipynb
  doc/tutorials/raspberry_electrophoresis/raspberry_electrophoresis.ipynb
  doc/tutorials/visualization/visualization.ipynb
  testsuite/scripts/tutorials/CMakeLists.txt
  testsuite/scripts/tutorials/test_charged_system.py
Labels: Documentation, automerge

#4177 utils: Better constraint for Utils::get
  src/utils/include/utils/get.hpp
Labels: automerge

#4171 LBGPU: Global Stress.
  src/core/grid_based_algorithms/electrokinetics_cuda.cu
  src/core/grid_based_algorithms/lb_interface.cpp
  src/core/grid_based_algorithms/lbgpu.cuh
  src/core/grid_based_algorithms/lbgpu.hpp
  src/core/grid_based_algorithms/lbgpu_cuda.cu
  src/core/virtual_sites/lb_inertialess_tracers_cuda.cu
  testsuite/python/lb.py
Labels: Improvement, Performance, automerge

#4181 Remove mis-use in Rattle
  src/core/CellStructure.cpp
  src/core/CellStructure.hpp
  src/core/Particle.hpp
  src/core/ghosts.cpp
  src/core/ghosts.hpp
  src/core/integrate.cpp
  src/core/rattle.cpp
  src/core/rattle.hpp
  src/core/unit_tests/Particle_test.cpp
Labels: CodeQuality, Core, automerge

#4165 Run NpT sanity checks at integration start
  src/core/npt.cpp
  src/core/thermostat.cpp
  testsuite/python/integrator_npt.py
Labels: BugFix, Core, automerge

#4191 Fix LB GPU grid resize code
  src/core/grid_based_algorithms/electrokinetics_cuda.cu
  src/core/grid_based_algorithms/lb_boundaries.cpp
  src/core/grid_based_algorithms/lb_interface.cpp
  src/core/grid_based_algorithms/lbgpu.cpp
  src/core/grid_based_algorithms/lbgpu.hpp
  src/core/grid_based_algorithms/lbgpu_cuda.cu
  src/core/virtual_sites/lb_inertialess_tracers_cuda.cu
  testsuite/python/lb.py
Labels: BugFix, Core, automerge

#4192 cuda: remove typedefs for floating point type.
  doc/sphinx/installation.rst
  src/config/features.def
  src/core/actor/DipolarBarnesHut.hpp
  src/core/actor/DipolarBarnesHut_cuda.cu
  src/core/actor/DipolarBarnesHut_cuda.cuh
  src/core/actor/DipolarDirectSum.hpp
  src/core/actor/DipolarDirectSum_cuda.cu
  src/core/actor/Mmm1dgpuForce.hpp
  src/core/actor/Mmm1dgpuForce_cuda.cu
  src/core/actor/specfunc_cuda.hpp
  src/core/grid_based_algorithms/electrokinetics.hpp
  src/core/grid_based_algorithms/electrokinetics_cuda.cu
  src/core/grid_based_algorithms/lb_boundaries.cpp
  src/core/grid_based_algorithms/lbgpu.hpp
  src/core/grid_based_algorithms/lbgpu_cuda.cu
  src/python/espressomd/electrokinetics.pxd
  src/python/espressomd/electrostatics.pxd
  src/python/espressomd/electrostatics.pyx
Labels: CodeQuality, Core, automerge

#4194 Improve code coverage
  src/core/electrostatics_magnetostatics/debye_hueckel.hpp
  src/core/grid_based_algorithms/lb_interface.cpp
  src/core/grid_based_algorithms/lb_interface.hpp
  src/utils/tests/CMakeLists.txt
  src/utils/tests/coordinate_transformation.cpp
  src/utils/tests/cylindrical_transformation.cpp
  testsuite/python/constraint_shape_based.py
  testsuite/python/electrostaticInteractions.py
  testsuite/python/galilei.py
Labels: Core, Testcase, automerge

#4193 utils: Made Array streamable
  src/utils/include/utils/Array.hpp
  src/utils/tests/Array_test.cpp
Labels: automerge
