Repository espressomd/espresso, pull requests merged in 2021-11, with the labels that each got.

#4386 Add Sphinx toggleprompt plugin
  .gitlab-ci.yml
  doc/sphinx/conf.py.in
  doc/sphinx/installation.rst
  requirements.txt
  src/python/espressomd/MDA_ESP/__init__.py
Labels: Documentation, DevOps, automerge

#4376 LB boundaries and OpenGL visualizer maintenance
  doc/sphinx/analysis.rst
  doc/sphinx/zrefs.bib
  src/core/grid_based_algorithms/lb_boundaries.cpp
  src/core/grid_based_algorithms/lb_boundaries.hpp
  src/core/grid_based_algorithms/lb_interface.cpp
  src/python/espressomd/lbboundaries.py
  src/python/espressomd/visualization_opengl.py
  testsuite/python/lb_interpolation.py
Labels: Documentation, Python, Core, automerge

#4387 Cython maintenance
  src/python/espressomd/CMakeLists.txt
  src/python/espressomd/script_interface.pyx
  src/script_interface/auto_parameters/AutoParameters.hpp
  testsuite/python/CMakeLists.txt
  testsuite/python/field_test.py
  testsuite/python/interactions_bonded_interface.py
  testsuite/python/script_interface.py
  testsuite/python/script_interface_object_params.py
Labels: BugFix, ScriptInterface, automerge

#4352 MC benchmarks
  maintainer/benchmarks/CMakeLists.txt
  maintainer/benchmarks/benchmarks.py
  maintainer/benchmarks/mc_acid_base_reservoir.py
  maintainer/benchmarks/runner.sh
  maintainer/benchmarks/suite.sh
  testsuite/scripts/benchmarks/CMakeLists.txt
  testsuite/scripts/benchmarks/test_mc_acid_base_reservoir.py
Labels: Python, automerge

#4388 Bugfix: Sampling efficiency in Widom insertion sample script
  samples/widom_insertion.py
Labels: Python, automerge

#4394 Script interface maintenance
  maintainer/CI/build_cmake.sh
  maintainer/benchmarks/CMakeLists.txt
  src/python/espressomd/collision_detection.pyx
  src/python/espressomd/interactions.pyx
  src/python/espressomd/particle_data.pyx
  src/python/espressomd/script_interface.pyx
  src/script_interface/Context.hpp
  src/script_interface/ContextManager.cpp
  src/script_interface/GlobalContext.hpp
  src/script_interface/LocalContext.hpp
  src/script_interface/interactions/BondedInteractions.hpp
  src/script_interface/interactions/bonded.hpp
  src/script_interface/lbboundaries/LBBoundary.hpp
  src/script_interface/object_container_mpi_guard.hpp
  src/script_interface/tests/GlobalContext_test.cpp
  src/script_interface/tests/LocalContext_test.cpp
  src/script_interface/tests/ObjectHandle_test.cpp
  src/script_interface/tests/ObjectList_test.cpp
  src/script_interface/tests/ObjectMap_test.cpp
  testsuite/python/interactions_bonded_interface.py
  testsuite/python/script_interface.py
  testsuite/python/test_checkpoint.py
Labels: Testcase, BugFix, ScriptInterface, automerge

#4393 Modernize Actors and LB testsuite
  src/config/features.def
  src/config/myconfig-default.hpp
  src/core/errorhandling.cpp
  src/core/errorhandling.hpp
  src/core/grid_based_algorithms/lb_boundaries.hpp
  src/core/grid_based_algorithms/lb_interface.cpp
  src/core/grid_based_algorithms/lb_interpolation.cpp
  src/core/grid_based_algorithms/lb_interpolation.hpp
  src/core/unit_tests/CMakeLists.txt
  src/core/unit_tests/lb_exceptions.cpp
  src/python/espressomd/actors.pyx
  src/python/espressomd/lb.pyx
  testsuite/python/engine_lb.py
  testsuite/python/lb.py
  testsuite/python/lb_boundary.py
  testsuite/python/lb_boundary_volume_force.py
  testsuite/python/lb_buoyancy_force.py
  testsuite/python/lb_density.py
  testsuite/python/lb_interpolation.py
  testsuite/python/lb_momentum_conservation.py
  testsuite/python/lb_poiseuille.py
  testsuite/python/lb_poiseuille_cylinder.py
  testsuite/python/lb_stats.py
  testsuite/python/lb_stokes_sphere.py
  testsuite/python/lb_streaming.py
  testsuite/python/lb_thermostat.py
  testsuite/python/lb_vtk.py
  testsuite/python/linear_momentum_lb.py
  testsuite/python/observable_cylindricalLB.py
  testsuite/python/observable_profileLB.py
Labels: Testcase, Python, automerge

#4396 Test cylindrical LB velocity profile observable
  src/core/EspressoSystemStandAlone.hpp
  src/core/event.cpp
  src/core/grid_based_algorithms/lb_interface.cpp
  src/script_interface/LocalContext.hpp
  src/script_interface/object_container_mpi_guard.hpp
  testsuite/python/CMakeLists.txt
  testsuite/python/lb_circular_couette.py
  testsuite/python/lb_poiseuille_cylinder.py
Labels: Testcase, Core, automerge
