Repository espressomd/espresso, pull requests merged in 2021-10, with the labels that each got.

#4364 Modernize Raspberry Electrophoresis Tutorial
  doc/tutorials/raspberry_electrophoresis/NotesForTutor.md
  doc/tutorials/raspberry_electrophoresis/raspberry_electrophoresis.ipynb
  testsuite/scripts/tutorials/test_raspberry_electrophoresis.py
Labels: Documentation, automerge

#4366 LB maintenance
  src/core/grid_based_algorithms/lattice.cpp
  src/core/grid_based_algorithms/lattice.hpp
  src/core/grid_based_algorithms/lb_boundaries.cpp
  src/core/grid_based_algorithms/lb_interface.cpp
  src/core/unit_tests/CMakeLists.txt
  src/core/unit_tests/Lattice_test.cpp
  src/shapes/include/shapes/Shape.hpp
  src/shapes/include/shapes/Union.hpp
  src/shapes/unit_tests/Wall_test.cpp
  src/utils/include/utils/Array.hpp
  src/utils/include/utils/Vector.hpp
  testsuite/python/lb_interpolation.py
  testsuite/python/lb_shear.py
  testsuite/python/lb_thermostat.py
  testsuite/python/save_checkpoint.py
  testsuite/python/test_checkpoint.py
Labels: Testcase, Core, automerge, CodeQuality

#4384 Fix division by zero returning incorrect vector
  src/shapes/src/Sphere.cpp
  src/shapes/unit_tests/CMakeLists.txt
  src/shapes/unit_tests/Sphere_test.cpp
Labels: Testcase, Core, BugFix, automerge
