Repository espressomd/espresso, pull requests merged in 2022-12, with the labels that each got.

#4623 Implement override_cutoff_check property for vs.
  doc/sphinx/particles.rst
  src/core/virtual_sites.cpp
  src/core/virtual_sites/VirtualSites.hpp
  src/script_interface/virtual_sites/VirtualSites.hpp
  testsuite/python/virtual_sites_relative.py
Labels: ScriptInterface, automerge

#4609 Allow multiple concurrent reaction methods
  src/core/reaction_methods/ReactionAlgorithm.cpp
  src/core/reaction_methods/ReactionAlgorithm.hpp
  src/core/reaction_methods/WidomInsertion.cpp
  testsuite/python/CMakeLists.txt
  testsuite/python/reaction_bookkeeping.py
Labels: Testcase, Core, BugFix, automerge

#4627 add ParticleDirectors observable
  doc/sphinx/analysis.rst
  src/core/observables/ParticleDirectors.hpp
  src/core/observables/ParticleTraits.hpp
  src/particle_observables/include/particle_observables/observable.hpp
  src/particle_observables/include/particle_observables/properties.hpp
  src/python/espressomd/observables.py
  src/script_interface/observables/initialize.cpp
  testsuite/python/observables.py
Labels: New Feature, automerge

#4628 fixed system.part.pairs()
  src/python/espressomd/particle_data.py
  testsuite/python/pairs.py
Labels: Python, BugFix, automerge

#4635 Remove deprecated numpy options
  testsuite/python/observable_profile.py
  testsuite/python/observable_profileLB.py
Labels: Python, automerge

#4637 Rewrite particle serialization mechanism
  src/script_interface/particle_data/ParticleHandle.cpp
  src/script_interface/particle_data/ParticleList.cpp
  testsuite/python/particle.py
  testsuite/python/save_checkpoint.py
  testsuite/python/test_checkpoint.py
Labels: Testcase, BugFix, ScriptInterface, automerge

#4631 Improve testing and code coverage
  .gitlab-ci.yml
  doc/sphinx/analysis.rst
  doc/sphinx/installation.rst
  doc/sphinx/system_setup.rst
  src/core/MpiCallbacks.hpp
  src/core/analysis/statistics.hpp
  src/core/electrostatics/specfunc.cpp
  src/core/electrostatics/specfunc.hpp
  src/core/magnetostatics/dipolar_direct_sum.cpp
  src/core/object-in-fluid/oif_local_forces.hpp
  src/core/p3m/common.cpp
  src/core/unit_tests/CMakeLists.txt
  src/core/unit_tests/MpiCallbacks_test.cpp
  src/core/unit_tests/Particle_serialization_test.cpp
  src/core/unit_tests/Verlet_list_test.cpp
  src/core/unit_tests/p3m_test.cpp
  src/core/unit_tests/specfunc_test.cpp
  src/python/espressomd/virtual_sites.py
  src/python/object_in_fluid/oif_classes.py
  src/utils/include/utils/index.hpp
  src/utils/tests/Factory_test.cpp
  src/utils/tests/gatherv_test.cpp
  testsuite/python/ek_eof_one_species.py
  testsuite/python/integrator_npt.py
  testsuite/python/oif_volume_conservation.py
  testsuite/python/save_checkpoint.py
  testsuite/python/test_checkpoint.py
  testsuite/python/virtual_sites_relative.py
Labels: Testcase, Documentation, automerge, CodeQuality

#4638 Bump GitHub Actions dependencies
  .github/actions/build_and_check/action.yml
  .github/workflows/deploy.yml
  .github/workflows/push_pull.yml
  doc/sphinx/installation.rst
Labels: Documentation, DevOps, automerge
