Repository espressomd/espresso, pull requests merged in 2022-08, with the labels that each got.

#4544 Test P3M stress tensor
  doc/bibliography.bib
  doc/sphinx/appendix.rst
  testsuite/python/CMakeLists.txt
  testsuite/python/coulomb_mixed_periodicity.py
  testsuite/python/p3m_madelung.py
Labels: Testcase, DevOps, automerge

#4548 Brownian dynamics: propagate spatially fixed yet freely rotatable particles
  src/core/thermostats/brownian_inline.hpp
  testsuite/python/brownian_dynamics.py
Labels: Core, BugFix, automerge

#4552 Invitation summer school 2022
  Readme.md
  doc/sphinx/conf.py.in
  doc/sphinx/introduction.rst
Labels: Documentation, automerge
