Repository espressomd/espresso, pull requests merged in 2022-07, with the labels that each got.

#4533 Fixed typo doc 8.1
  doc/sphinx/inter_bonded.rst
Labels: Documentation, automerge

#4530 Update version to 4.3-dev
  CMakeLists.txt
  NEWS
  doc/sphinx/installation.rst
  src/config/version.hpp.in
  src/core/electrostatics/coulomb.cpp
Labels: Documentation, automerge

#4531 Create .gitpod.yml
  .gitpod.yml
  Readme.md
  doc/sphinx/installation.rst
  doc/sphinx/running.rst
  doc/tutorials/constant_pH/constant_pH.ipynb
  doc/tutorials/convert.py
  doc/tutorials/electrokinetics/electrokinetics.ipynb
  doc/tutorials/error_analysis/error_analysis_part1.ipynb
  doc/tutorials/error_analysis/error_analysis_part2.ipynb
  doc/tutorials/lattice_boltzmann/lattice_boltzmann_theory.ipynb
  doc/tutorials/polymers/polymers.ipynb
  doc/tutorials/raspberry_electrophoresis/raspberry_electrophoresis.ipynb
Labels: Documentation, New Feature, automerge

#4535 Remove MDAnalysis bindings
  doc/sphinx/installation.rst
  doc/sphinx/io.rst
  requirements.txt
  samples/MDAnalysisIntegration.py
  src/python/espressomd/CMakeLists.txt
  src/python/espressomd/MDA_ESP/__init__.py
  testsuite/python/CMakeLists.txt
  testsuite/python/mdanalysis.py
  testsuite/scripts/samples/CMakeLists.txt
  testsuite/scripts/samples/test_MDAnalysisIntegration.py
Labels: Python, automerge

#4538 Fix minor regressions in 4.2.0
  src/scafacos/src/Scafacos.cpp
  src/utils/tests/integral_parameter_test.cpp
Labels: Core, automerge

#4532 CMake refactor
  .codecov.yml
  .gitlab-ci.yml
  CMakeLists.txt
  cmake/FindCUDACompilerClang.cmake
  cmake/FindCUDACompilerNVCC.cmake
  doc/sphinx/installation.rst
  maintainer/CI/dox_warnings.sh
  src/core/CMakeLists.txt
  src/core/electrostatics/coulomb.cpp
  src/core/electrostatics/coulomb.hpp
  src/core/forces.cpp
  src/core/interactions.cpp
  src/core/io/writer/CMakeLists.txt
  src/core/magnetostatics/dipoles.cpp
  src/core/magnetostatics/dipoles.hpp
  src/core/nonbonded_interactions/nonbonded_interaction_data.cpp
  src/core/nonbonded_interactions/thole.hpp
  src/core/p3m/CMakeLists.txt
  src/core/scafacos/CMakeLists.txt
  src/core/stokesian_dynamics/CMakeLists.txt
  src/python/espressomd/CMakeLists.txt
  src/script_interface/CMakeLists.txt
  src/script_interface/tests/CMakeLists.txt
  src/utils/CMakeLists.txt
  src/utils/tests/CMakeLists.txt
Labels: CMake, DevOps, automerge

#4539 Hide particle struct layout
  src/core/Particle.hpp
  src/core/ghosts.cpp
  src/core/observables/ParticleAngularVelocities.hpp
  src/core/observables/ParticleBodyAngularVelocities.hpp
  src/core/observables/ParticleBodyVelocities.hpp
  src/core/observables/ParticleDistances.hpp
  src/core/observables/ParticleForces.hpp
  src/core/observables/ParticlePositions.hpp
  src/core/observables/ParticleTraits.hpp
  src/core/observables/ParticleVelocities.hpp
  src/particle_observables/include/particle_observables/observable.hpp
  src/particle_observables/include/particle_observables/properties.hpp
Labels: Core, automerge
