Repository espressomd/espresso, pull requests merged in 2022-04, with the labels that each got.

#4480 Rewrite H5MD module
  doc/sphinx/io.rst
  samples/h5md_trajectory.py
  src/core/BoxGeometry.hpp
  src/core/CellStructure.cpp
  src/core/io/writer/h5md_core.cpp
  src/core/io/writer/h5md_core.hpp
  src/core/io/writer/h5md_specification.cpp
  src/core/io/writer/h5md_specification.hpp
  src/core/lees_edwards/lees_edwards.hpp
  src/core/virtual_sites/VirtualSitesRelative.cpp
  src/python/espressomd/io/writer/__init__.py
  src/python/espressomd/io/writer/h5md.py
  src/python/espressomd/script_interface.pyx
  src/script_interface/Variant.hpp
  src/script_interface/get_value.hpp
  src/script_interface/h5md/h5md.cpp
  src/script_interface/h5md/h5md.hpp
  src/script_interface/packed_variant.hpp
  src/script_interface/tests/get_value_test.cpp
  testsuite/python/h5md.py
  testsuite/python/save_checkpoint.py
  testsuite/python/test_checkpoint.py
  testsuite/scripts/samples/CMakeLists.txt
  testsuite/scripts/samples/test_h5md_trajectory.py
Labels: Testcase, Documentation, New Feature, BugFix, ApiChange, automerge

#4489 Python maintenance
  .github/workflows/push_pull.yml
  .gitlab-ci.yml
  CMakeLists.txt
  doc/sphinx/inter_bonded.rst
  doc/sphinx/system_setup.rst
  maintainer/CI/build_cmake.sh
  maintainer/CI/deploy_tutorials.py
  maintainer/CI/dox_warnings.py
  maintainer/CI/jupyter_warnings.py
  maintainer/benchmarks/benchmarks.py
  src/core/bonded_interactions/bonded_tab.hpp
  src/core/bonded_interactions/dihedral.hpp
  src/core/lees_edwards/protocols.hpp
  src/core/unit_tests/lees_edwards_test.cpp
  src/python/espressomd/analyze.pyx
  src/python/espressomd/lees_edwards.py
  src/script_interface/lees_edwards/OscillatoryShear.hpp
  testsuite/python/analyze_chains.py
  testsuite/python/cluster_analysis.py
  testsuite/python/coulomb_cloud_wall.py
  testsuite/python/coulomb_cloud_wall_duplicated.py
  testsuite/python/coulomb_mixed_periodicity.py
  testsuite/python/coulomb_tuning.py
  testsuite/python/decorators.py
  testsuite/python/dipolar_direct_summation.py
  testsuite/python/dipolar_mdlc_p3m_scafacos_p2nfft.py
  testsuite/python/ek_eof_one_species.py
  testsuite/python/h5md.py
  testsuite/python/integrator_npt.py
  testsuite/python/integrator_npt_stats.py
  testsuite/python/interactions_dihedral.py
  testsuite/python/lb_vtk.py
  testsuite/python/lees_edwards.py
  testsuite/python/lj.py
  testsuite/python/mdanalysis.py
  testsuite/python/mmm1d.py
  testsuite/python/npt_thermostat.py
  testsuite/python/oif_volume_conservation.py
  testsuite/python/p3m_electrostatic_pressure.py
  testsuite/python/save_checkpoint.py
  testsuite/python/scafacos_dipoles_1d_2d.py
  testsuite/python/script_interface.py
  testsuite/python/sigint.py
  testsuite/python/stokesian_dynamics.py
  testsuite/python/test_checkpoint.py
  testsuite/python/tests_common.py
  testsuite/python/unittest_generator.py
  testsuite/scripts/importlib_wrapper.py
  testsuite/scripts/samples/test_ekboundaries.py
  testsuite/scripts/samples/test_immersed_boundary.py
  testsuite/scripts/samples/test_object_in_fluid__motivation.py
  testsuite/scripts/samples/test_save_checkpoint.py
  testsuite/scripts/test_importlib_wrapper.py
  testsuite/scripts/tutorials/test_convert.py
Labels: Testcase, Python, DevOps, automerge

#4492 Safe exception handling during type conversion
  src/python/espressomd/script_interface.pyx
  testsuite/python/script_interface.py
Labels: BugFix, ScriptInterface, automerge

#4484 Collision detection maintenance
  src/core/collision.cpp
  src/core/collision.hpp
  src/python/espressomd/collision_detection.py
  src/python/espressomd/system.pyx
  src/script_interface/collision_detection/CollisionDetection.hpp
  testsuite/python/CMakeLists.txt
  testsuite/python/collision_detection.py
  testsuite/python/collision_detection_interface.py
Labels: Testcase, Improvement, BugFix, ScriptInterface, automerge

#4501 Bump cmake-format requirements
  .gitlab-ci.yml
  maintainer/format/cmake-format.sh
  requirements.txt
  testsuite/python/mmm1d_gpu.py
Labels: DevOps, automerge

#4503 fix math in error calculation
  samples/gibbs_ensemble/Readme.md
  samples/gibbs_ensemble/create_fits.py
  samples/gibbs_ensemble/run_sim.py
Labels: Python, automerge

#4470 LB coupling for RegularDecomposition without ghost shifts.
  src/core/RegularDecomposition.cpp
  src/core/RegularDecomposition.hpp
  src/core/grid_based_algorithms/lb.cpp
  src/core/grid_based_algorithms/lb_particle_coupling.cpp
  src/core/grid_based_algorithms/lb_particle_coupling.hpp
  src/core/virtual_sites/lb_inertialess_tracers.cpp
  testsuite/python/CMakeLists.txt
  testsuite/python/engine_lb.py
  testsuite/python/engine_lb_nsquare.py
  testsuite/python/lb_momentum_conservation.py
  testsuite/python/lb_momentum_conservation_nsquare.py
  testsuite/python/lb_stats.py
  testsuite/python/lb_stats_nsquare.py
  testsuite/python/random_pairs.py
Labels: Core, BugFix, automerge
