Repository espressomd/espresso, pull requests merged in 2022-06, with the labels that each got.

#4520 Remove time count in every iteration of sim run
  samples/visualization_ljliquid.py
Labels: Python, automerge

#4522 Add support for JupyterLab
  doc/sphinx/installation.rst
  doc/sphinx/running.rst
  doc/tutorials/Readme.md
  doc/tutorials/active_matter/active_matter.ipynb
  doc/tutorials/charged_system/CMakeLists.txt
  doc/tutorials/charged_system/charged_system.ipynb
  doc/tutorials/constant_pH/constant_pH.ipynb
  doc/tutorials/convert.py
  doc/tutorials/electrokinetics/CMakeLists.txt
  doc/tutorials/electrokinetics/electrokinetics.ipynb
  doc/tutorials/electrokinetics/figures/profiles.png
  doc/tutorials/electrokinetics/scripts/plot.py
  doc/tutorials/error_analysis/error_analysis_part1.ipynb
  doc/tutorials/error_analysis/error_analysis_part2.ipynb
  doc/tutorials/ferrofluid/ferrofluid_part1.ipynb
  doc/tutorials/ferrofluid/ferrofluid_part2.ipynb
  doc/tutorials/ferrofluid/ferrofluid_part3.ipynb
  doc/tutorials/langevin_dynamics/langevin_dynamics.ipynb
  doc/tutorials/lattice_boltzmann/figures/latticeboltzmann-grid.pdf
  doc/tutorials/lattice_boltzmann/figures/poiseuille.png
  doc/tutorials/lattice_boltzmann/lattice_boltzmann_poiseuille_flow.ipynb
  doc/tutorials/lennard_jones/lennard_jones.ipynb
  doc/tutorials/polymers/polymers.ipynb
  doc/tutorials/raspberry_electrophoresis/raspberry_electrophoresis.ipynb
  doc/tutorials/visualization/visualization.ipynb
  testsuite/scripts/tutorials/test_charged_system.py
  testsuite/scripts/tutorials/test_electrokinetics.py
  testsuite/scripts/tutorials/test_ferrofluid_1.py
Labels: Documentation, Python, automerge, CodeQuality

#4523 Skip short-range non-bonded loop when no IA is active
  src/core/short_range_loop.hpp
Labels: Core, automerge

#4526 Support recent Linux distributions
  .gitlab-ci.yml
  cmake/FindCUDACompilerClang.cmake
  doc/sphinx/_static/custom.css
  doc/sphinx/conf.py.in
  doc/sphinx/installation.rst
  maintainer/CI/build_cmake.sh
  src/core/accumulators/Correlator.cpp
  src/core/accumulators/Correlator.hpp
  src/core/cell_system/CellStructure.hpp
  src/core/cells.cpp
  src/core/cuda_interface.cpp
  src/core/energy.cpp
  src/core/grid_based_algorithms/electrokinetics_cuda.cu
  src/core/grid_based_algorithms/lb_boundaries.cpp
  src/core/io/writer/h5md_core.cpp
  src/python/espressomd/utils.pyx
  src/script_interface/GlobalContext.hpp
  src/script_interface/LocalContext.hpp
  src/script_interface/tests/ParallelExceptionHandler_test.cpp
  src/shapes/src/Rhomboid.cpp
  src/utils/tests/serialization_test.cpp
  testsuite/python/h5md.py
Labels: DevOps, automerge
