Repository espressomd/espresso, pull requests merged in 2023-06, with the labels that each got.

#4739 Code maintenance
  .gitpod.yml
  Readme.md
  doc/sphinx/lb.rst
  maintainer/benchmarks/lb.py
  src/core/bond_breakage/bond_breakage.cpp
  src/core/bond_breakage/bond_breakage.hpp
  src/core/bonded_interactions/thermalized_bond_kernel.hpp
  src/core/forces_inline.hpp
  src/core/unit_tests/lb_particle_coupling_test.cpp
  src/python/espressomd/interactions.py
  src/python/espressomd/script_interface.pxd
  src/python/espressomd/script_interface.pyx
  src/python/espressomd/thermostat.pyx
  src/python/espressomd/utils.pxd
  src/python/espressomd/utils.pyx
  src/script_interface/ObjectHandle.hpp
  src/script_interface/bond_breakage/BreakageSpecs.hpp
  src/script_interface/interactions/BondedInteractions.hpp
  src/script_interface/interactions/NonBondedInteraction.hpp
  src/script_interface/interactions/NonBondedInteractions.hpp
  src/utils/include/utils/integral_parameter.hpp
  src/walberla_bridge/include/walberla_bridge/VTKHandle.hpp
  testsuite/python/interactions_non-bonded_interface.py
  testsuite/python/lb.py
  testsuite/python/lb_lees_edwards.py
Labels: automerge

#4626 Dipole field calculation in parallel with direct sum
  doc/sphinx/installation.rst
  doc/sphinx/magnetostatics.rst
  maintainer/configs/maxset.hpp
  src/config/features.def
  src/core/Particle.hpp
  src/core/energy.cpp
  src/core/energy.hpp
  src/core/magnetostatics/dipolar_direct_sum.cpp
  src/core/magnetostatics/dipolar_direct_sum.hpp
  src/core/magnetostatics/dipoles.cpp
  src/core/magnetostatics/dipoles.hpp
  src/core/observables/ParticleDipoleFields.hpp
  src/core/observables/ParticleTraits.hpp
  src/particle_observables/include/particle_observables/observable.hpp
  src/particle_observables/include/particle_observables/properties.hpp
  src/python/espressomd/analyze.py
  src/python/espressomd/observables.py
  src/python/espressomd/particle_data.py
  src/script_interface/analysis/Analysis.cpp
  src/script_interface/observables/initialize.cpp
  src/script_interface/particle_data/ParticleHandle.cpp
  testsuite/python/CMakeLists.txt
  testsuite/python/dipolar_interface.py
  testsuite/python/dipole_field_tracking.py
  testsuite/python/observables.py
Labels: New Feature, automerge

#4741 Introduce a System class in the core
  src/core/CMakeLists.txt
  src/core/CudaDeviceAllocator.hpp
  src/core/EspressoSystemInterface.cpp
  src/core/EspressoSystemInterface.hpp
  src/core/EspressoSystemInterface_cuda.cu
  src/core/EspressoSystemStandAlone.cpp
  src/core/SystemInterface.hpp
  src/core/cuda/CudaHostAllocator.cu
  src/core/cuda/CudaHostAllocator.hpp
  src/core/cuda/common_cuda.cu
  src/core/cuda/init.cpp
  src/core/cuda/init.hpp
  src/core/cuda/init_cuda.cu
  src/core/cuda/utils.cuh
  src/core/cuda/utils.hpp
  src/core/cuda_common_cuda.cu
  src/core/cuda_interface.cpp
  src/core/cuda_interface.hpp
  src/core/electrostatics/mmm1d_gpu.cpp
  src/core/electrostatics/mmm1d_gpu.hpp
  src/core/electrostatics/mmm1d_gpu_cuda.cu
  src/core/electrostatics/p3m_gpu.cpp
  src/core/electrostatics/p3m_gpu.hpp
  src/core/electrostatics/p3m_gpu_cuda.cu
  src/core/electrostatics/p3m_gpu_error_cuda.cu
  src/core/energy.cpp
  src/core/event.cpp
  src/core/forces.cpp
  src/core/magnetostatics/barnes_hut_gpu.cpp
  src/core/magnetostatics/barnes_hut_gpu_cuda.cu
  src/core/magnetostatics/dipolar_direct_sum_gpu.cpp
  src/core/magnetostatics/dipolar_direct_sum_gpu_cuda.cu
  src/core/serialization/CUDA_particle_data.hpp
  src/core/system/GpuParticleData.cpp
  src/core/system/GpuParticleData.hpp
  src/core/system/GpuParticleData_cuda.cu
  src/core/system/ResourceCleanup.hpp
  src/core/system/System.cpp
  src/core/system/System.hpp
  src/core/unit_tests/CMakeLists.txt
  src/core/unit_tests/EspressoSystemInterface_test.cpp
  src/core/unit_tests/EspressoSystem_test.cpp
  src/core/unit_tests/ResourceCleanup_test.cpp
  src/python/espressomd/system.py
  src/script_interface/electrostatics/CoulombP3MGPU.hpp
  src/script_interface/system/CMakeLists.txt
  src/script_interface/system/CudaInitHandle.cpp
  src/script_interface/system/Globals.cpp
  src/script_interface/system/Globals.hpp
  src/script_interface/system/System.cpp
  src/script_interface/system/System.hpp
  src/script_interface/system/SystemFacade.hpp
  src/script_interface/system/initialize.cpp
Labels: Core, Improvement, automerge
