Repository espressomd/espresso, pull requests merged in 2023-11, with the labels that each got.

#4813 Fix OIF force summary function
  src/python/object_in_fluid/oif_classes.py
  testsuite/python/oif_volume_conservation.py
Labels: Python, BugFix, automerge

#4824 Fix unstable electrode tutorial
  doc/tutorials/electrodes/electrodes_part2.ipynb
  testsuite/scripts/tutorials/CMakeLists.txt
  testsuite/scripts/tutorials/test_electrodes_2.py
Labels: Documentation, automerge

#4830 Migration to Jupyterlab
  .github/workflows/push_pull.yml
  .gitlab-ci.yml
  doc/sphinx/conf.py.in
  doc/sphinx/installation.rst
  doc/sphinx/running.rst
  doc/tutorials/CMakeLists.txt
  doc/tutorials/Readme.md
  doc/tutorials/active_matter/active_matter.ipynb
  doc/tutorials/charged_system/charged_system.ipynb
  doc/tutorials/constant_pH/constant_pH.ipynb
  doc/tutorials/convert.py
  doc/tutorials/electrodes/electrodes_part1.ipynb
  doc/tutorials/electrodes/electrodes_part2.ipynb
  doc/tutorials/electrokinetics/electrokinetics.ipynb
  doc/tutorials/error_analysis/error_analysis_part1.ipynb
  doc/tutorials/error_analysis/error_analysis_part2.ipynb
  doc/tutorials/ferrofluid/ferrofluid_part1.ipynb
  doc/tutorials/ferrofluid/ferrofluid_part2.ipynb
  doc/tutorials/ferrofluid/ferrofluid_part3.ipynb
  doc/tutorials/grand_canonical_monte_carlo/grand_canonical_monte_carlo.ipynb
  doc/tutorials/langevin_dynamics/langevin_dynamics.ipynb
  doc/tutorials/lattice_boltzmann/lattice_boltzmann_poiseuille_flow.ipynb
  doc/tutorials/lattice_boltzmann/lattice_boltzmann_sedimentation.ipynb
  doc/tutorials/lattice_boltzmann/lattice_boltzmann_theory.ipynb
  doc/tutorials/lennard_jones/lennard_jones.ipynb
  doc/tutorials/polymers/polymers.ipynb
  doc/tutorials/raspberry_electrophoresis/raspberry_electrophoresis.ipynb
  doc/tutorials/visualization/visualization.ipynb
  doc/tutorials/widom_insertion/widom_insertion.ipynb
  maintainer/CI/build_cmake.sh
  maintainer/CI/deploy_tutorials.py
  requirements.txt
  testsuite/scripts/tutorials/test_convert.py
Labels: Documentation, DevOps, automerge
