Repository espressomd/espresso, pull requests merged in 2024-04, with the labels that each got.

#4901 Disable box length reset when particles are present
  samples/h5md_trajectory.py
  src/core/constraints/Constraints.hpp
  src/core/ek/EKNone.hpp
  src/core/ek/EKWalberla.hpp
  src/core/ek/Solver.cpp
  src/core/ek/Solver.hpp
  src/core/lb/LBNone.hpp
  src/core/lb/LBWalberla.hpp
  src/core/lb/Solver.cpp
  src/core/lb/Solver.hpp
  src/core/system/System.cpp
  src/core/system/System.hpp
  src/core/unit_tests/ek_interface_test.cpp
  src/core/unit_tests/lb_particle_coupling_test.cpp
  src/script_interface/system/System.cpp
  testsuite/python/analyze_chains.py
  testsuite/python/array_properties.py
  testsuite/python/constraint_shape_based.py
  testsuite/python/coulomb_interface.py
  testsuite/python/coulomb_mixed_periodicity.py
  testsuite/python/dds-and-bh-gpu.py
  testsuite/python/dipolar_direct_summation.py
  testsuite/python/dipolar_interface.py
  testsuite/python/dipolar_p3m.py
  testsuite/python/ek_interface.py
  testsuite/python/elc_vs_analytic.py
  testsuite/python/electrostatic_interactions.py
  testsuite/python/lb.py
  testsuite/python/mmm1d.py
  testsuite/python/npt_thermostat.py
  testsuite/python/p3m_tuning_exceptions.py
  testsuite/python/rescale.py
  testsuite/python/scafacos_dipoles_1d_2d.py
  testsuite/python/scafacos_interface.py
  testsuite/python/virtual_sites_tracers_common.py
Labels: Core, BugFix, ApiChange, automerge

#4914 Improve documentation of integrators and thermostats
  doc/sphinx/integration.rst
Labels: Documentation, automerge

#4915 Unify steepest descent in the tutorials
  doc/sphinx/integration.rst
  doc/tutorials/charged_system/charged_system.ipynb
  doc/tutorials/constant_pH/constant_pH.ipynb
  doc/tutorials/electrodes/electrodes_part2.ipynb
  doc/tutorials/ferrofluid/ferrofluid_part1.ipynb
  doc/tutorials/ferrofluid/ferrofluid_part2.ipynb
  doc/tutorials/ferrofluid/ferrofluid_part3.ipynb
  doc/tutorials/lennard_jones/lennard_jones.ipynb
  doc/tutorials/polymers/polymers.ipynb
  doc/tutorials/widom_insertion/widom_insertion.ipynb
Labels: Documentation, CodingDay, automerge
