Repository espressomd/espresso, pull requests merged in 2024-12, with the labels that each got.

#5015 Update P3MGPU documentation
  doc/sphinx/electrostatics.rst
Labels: Documentation, automerge

#5016 Fix SimplePore distance function
  .github/actions/build_and_check/action.yml
  src/shapes/src/SimplePore.cpp
  testsuite/python/simple_pore.py
Labels: Testcase, BugFix, automerge

#5017 Add new P3M tuning options
  doc/doxygen/Doxyfile.in
  src/core/electrostatics/elc.cpp
  src/core/electrostatics/p3m.cpp
  src/core/electrostatics/p3m.impl.hpp
  src/core/magnetostatics/dlc.cpp
  src/core/magnetostatics/dp3m.cpp
  src/core/magnetostatics/dp3m.impl.hpp
  src/core/p3m/TuningAlgorithm.cpp
  src/core/p3m/TuningAlgorithm.hpp
  src/core/p3m/common.hpp
  src/core/p3m/data_struct.hpp
  src/core/p3m/influence_function.hpp
  src/core/p3m/influence_function_dipolar.hpp
  src/core/unit_tests/EspressoSystemStandAlone_test.cpp
  src/core/unit_tests/p3m_test.cpp
  src/python/espressomd/electrostatics.py
  src/python/espressomd/magnetostatics.py
  src/script_interface/electrostatics/CoulombP3M.hpp
  src/script_interface/magnetostatics/DipolarP3M.hpp
  testsuite/python/p3m_tuning_exceptions.py
  testsuite/python/save_checkpoint.py
  testsuite/python/test_checkpoint.py
Labels: New Feature, BugFix, automerge

#5018 Simplify build system targets
  CMakeLists.txt
  src/CMakeLists.txt
  src/core/CMakeLists.txt
  src/instrumentation/CMakeLists.txt
  src/script_interface/CMakeLists.txt
  src/walberla_bridge/CMakeLists.txt
  src/walberla_bridge/src/electrokinetics/generated_kernels/CMakeLists.txt
  src/walberla_bridge/src/electrokinetics/reactions/generated_kernels/CMakeLists.txt
  src/walberla_bridge/src/lattice_boltzmann/generated_kernels/CMakeLists.txt
  src/walberla_bridge/tests/CMakeLists.txt
Labels: CMake, automerge
