Repository espressomd/espresso, pull requests merged in 2025-03, with the labels that each got.

#5047 Add storage-agnostic function to add bonds between particles
  .gitlab-ci.yml
  src/core/CMakeLists.txt
  src/core/bonds.cpp
  src/core/bonds.hpp
  src/core/collision_detection/BindAtPointOfCollision.cpp
  src/core/collision_detection/BindCenters.cpp
  src/core/collision_detection/utils.hpp
  src/script_interface/particle_data/ParticleHandle.cpp
Labels: Core, automerge

#5019 Sympy potential
  doc/sphinx/installation.rst
  doc/sphinx/inter_non-bonded.rst
  doc/tutorials/CMakeLists.txt
  src/python/espressomd/interactions.py
  testsuite/python/tabulated.py
Labels: New Feature, automerge

#5052 Fix regressions from the last CI/CD refactoring
  .gitlab-ci.yml
Labels: DevOps, automerge

#5045 Add DPD contribution to the pressure
  src/core/Observable_stat.cpp
  src/core/Observable_stat.hpp
  src/core/dpd.cpp
  src/core/dpd.hpp
  src/core/pressure.cpp
  src/python/espressomd/analyze.py
  src/script_interface/analysis/ObservableStat.cpp
  testsuite/python/analyze_energy.py
  testsuite/python/dpd.py
Labels: CodingDay, automerge

#5062 Restructure installation documentation
  INSTALL
  Readme.md
  doc/bibliography.bib
  doc/sphinx/conf.py.in
  doc/sphinx/electrostatics.rst
  doc/sphinx/installation.rst
  doc/sphinx/running.rst
Labels: Documentation, automerge
